(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib._20 = function() {
	this.initialize(img._20);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,52,40);


(lib._4v_s = function() {
	this.initialize(img._4v_s);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,208,33);


(lib.allview_s = function() {
	this.initialize(img.allview_s);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,194,41);


(lib.BG = function() {
	this.initialize(img.BG);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,728,90);


(lib.C1_MOTOR = function() {
	this.initialize(img.C1_MOTOR);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,62,90);


(lib.C2_MOTOR = function() {
	this.initialize(img.C2_MOTOR);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,113,90);


(lib.C3_MOTOR = function() {
	this.initialize(img.C3_MOTOR);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,119,90);


(lib.C3_txt1_s = function() {
	this.initialize(img.C3_txt1_s);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,231,35);


(lib.C3_txt2_s = function() {
	this.initialize(img.C3_txt2_s);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,207,37);


(lib.LOGO = function() {
	this.initialize(img.LOGO);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,50,40);


(lib.OSZ_LOGO = function() {
	this.initialize(img.OSZ_LOGO);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,71,23);


(lib.t0_s = function() {
	this.initialize(img.t0_s);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,182,35);


(lib.t1_s = function() {
	this.initialize(img.t1_s);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,290,41);


(lib.usb_s = function() {
	this.initialize(img.usb_s);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,169,39);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.speed = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 圖層_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ah3ALIAJgeIDmATIAAAUg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.speed, new cjs.Rectangle(-12,-2,24.1,4), null);


(lib.Shine = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 圖層 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(255,255,255,0)","#FFFFFF","rgba(255,255,255,0)"],[0.008,0.482,1],-11,0,11,0).s().p("AhtFgIAAq/IDbAAIAAK/g");
	this.shape.setTransform(11,35.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Shine, new cjs.Rectangle(0,0,22,70.4), null);


(lib.OSZ_LOGO_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 圖層_1
	this.instance = new lib.OSZ_LOGO();
	this.instance.parent = this;
	this.instance.setTransform(-35.5,-11.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.OSZ_LOGO_1, new cjs.Rectangle(-35.5,-11.5,71,23), null);


(lib.C3_txt2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 圖層_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FEF9A0").s().p("AI5AxIAAgZIgBgNQgEgOgFgGQgGgHgGgBQgHAAgGAGQgHAHgCANIgBAMIAAAcIgqAAIAAgIQABgSAEgQQADgJAEgJQAEgIAJgJQAIgGAJgDQAKgEAKgBQAMAAAMAFQAMAFAIAIQAGAIAFAJQAEAIACAKQAEAPAAAPIABAIgAGkAxIAAgZIgBgNQgDgNgFgHQgGgHgHgBQgHgBgGAHQgGAHgDANIgBAMIAAAcIgpAAIAAgIQABgSAEgQIAGgSQAFgKAIgHQAJgGAIgDQALgEAJgBQANAAALAFQALAFAJAIQAHAJAEAIIAHASQADAQABAOIAAAIgAEQAxIAAgZIgCgNQgDgOgFgGQgFgHgIgBQgGAAgHAGQgGAHgCANIgCAMIAAAcIgpAAIAAgIQABgSAEgQQACgJAFgJQAEgJAJgIQAIgGAJgDQAKgEAJgBQANAAALAFQAMAFAIAIQAGAIAFAJQAEAIADAKQAEAPAAAPIAAAIgAArAxIgFgEQgGgDgFABQgFAAgFACIgEAEIgsAAIAJhHQABgHAGgFQAEgFAHABIBaAAIAAAXIhCAAIgCABIgCADIgFAmQAFgEAGgCIAMgDIARACQAIACAIAFQAIAGAHAKIADAGgAhcAxIAAgGIgDgIIgDgEIgFgEIAAAWIgIAAIAAgWIgDABIgEADQgFAEAAAHQgBACACAFIABAAIgcAAIAAgBQAAgOAGgHIAGgHIAJgFIAJgCIAIgCIAAgKIAIAAIAAAKQAMACAIAEIAHAGIAGAGQAGAJAAALgAjoAxIAAgGIgbAAIgBAGIghAAIAAg/QAAgKAGgGQADgDAFgCIAMgCQAUgBAZgDIAtgHIAAAVIgmAHIgmAEQgBAAAAABQgBAAAAAAQgBAAAAAAQgBABAAAAQgBAAAAABQAAAAgBABQAAAAAAABQAAAAAAABIAAAgIBXAAIAAAVIgcAAIAAAGgAk8AxIAQgGIAAAGgAleAxIAAgnIgWAAIAAgUIAWAAIAAglIAgAAIAAAlIASAAIAAAUIgSAAIAAAngAnAAxIAAgBIgyAAIAAABIggAAIAAhLQAAgIAGgGQADgDADgCIAIgBIBKAAQAJAAAGAGQAGAGAAAHIAABMgAnyAcIAyAAIAAgRIgyAAgAnwgZQgBABAAAAQAAAAAAABQgBAAAAAAQAAABAAAAIAAAOIAyAAIAAgOQAAAAAAgBQAAAAAAAAQAAgBgBAAQAAAAAAgBQAAAAgBAAQAAAAAAgBQgBAAAAAAQgBAAAAAAIgpAAQgBAAAAAAQgBAAAAAAQAAABgBAAQAAAAAAAAgApcAxIAAgPIAQAAIAAg1IgVAAIAAgVIBIAAIAAAVIgTAAIAAA1IAOAAIAAAPg");
	this.shape.setTransform(35.1,-6.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#D7D7D7","#FFFFFF"],[0,0.549],0,6.4,0,-7.3).s().p("AgLBFIAAgSIg4AAIAAgOIA4AAIAAgKIglAAIgEgBQgDgBgCgDIgCgDIAAgGIAAgjQAAgEACgDIAEgEIAFgBIAlAAIAAgJIg2AAIAAgOIA2AAIAAgLIAWAAIAAALIA3AAIAAAOIg3AAIAAAJIAmAAQAFABADADQAEAEAAAEIAAAnIgCAEIgDADIgDADIgEAAIgmAAIAAAKIA5AAIAAAOIg5AAIAAASgAALANIAYAAIACgBIABgCIAAgIIgbAAgAglAKIABACIACABIAXAAIAAgLIgaAAgAALgJIAbAAIAAgHIgBgCQAAgBgBAAQAAAAAAgBQAAAAgBAAQAAAAAAAAIgYAAgAgkgSIgBACIAAAHIAaAAIAAgLIgXAAIgCACg");
	this.shape_1.setTransform(-40.9,1.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#D7D7D7","#FFFFFF"],[0,0.549],0,6.4,0,-7.2).s().p("AAfBFIgEgMIAPAAIACgBIABgDIAAgFIglAAIAAAVIgSAAIAAgVIgHAAIAAgNIAHAAIAAgZQAAgGAEgEQAEgCAFAAIANAAIAAgGIgfAAIAAgMIANAAIAAgHIgKAAIAAgMIAKAAIAAgHIgMAAIAAgMIAMAAIAAgKIAUAAIAAAKIAPAAIAAgKIAVAAIAAAKIAPAAIAAAMIgPAAIAAAHIAMAAIAAAMIgMAAIAAAHIAQAAIAAAMIghAAIAAAGIAOAAIAGABIADACQAEADAAAHIAAAYIAHAAIAAANIgHAAIAAAMIgCAFQgBACgDABQgCABgFAAgAAlAjIAIAAIAAgHIgIAAgAAIAjIAIAAIAAgHIgIAAgAAlARIAIAAIAAgEIgBgBIgCgBIgFAAgAAIAMIAAABIAAAEIAIAAIAAgGIgGAAgAASgUIAPAAIAAgHIgPAAgAASgnIAPAAIAAgHIgPAAgAgjBFIgFgfIASAAIAGAfgAhGBFIAFgPIADgQIATAAIgGAfgAg3AgQgFgBgDgCQgDgDAAgGIAAhLQAAgEACgDQAEgDAEAAIAbAAQAFAAADADQADADgBAFIAABLQAAAFgCADQgDADgFAAgAguAQIAAABIACAAIAEAAQAAAAABAAQAAAAAAAAQAAAAAAAAQABgBAAAAIAAgNIgIAAgAgugKIAIAAIAAgOIgIAAgAgugyIAAABIAAAMIAIAAIAAgMQAAgBgBAAQAAAAAAgBQAAAAAAAAQgBAAAAAAIgEAAg");
	this.shape_2.setTransform(-56.9,1.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["#D7D7D7","#FFFFFF"],[0,0.549],0,6.4,0,-7.3).s().p("AhDBDIAAgNIA4AAIAAgmIgyAAIAAgOIAyAAIAAgUIgdAAIgGAKIgbAAQAJgPAGgLIALgYQACgEADgCQADgDAEAAIBFAAQAFAAADADQAEACACADIAaAzIgcAAIgGgKIgcAAIAAAUIAyAAIAAAOIgyAAIAAAmIA3AAIAAANgAgZgxIgEAJIgFAIIBEAAIgIgRIgCgCIgDgBIgqAAQgDAAgBADgAATAvIARgYIAZAAIgPAYgAgtAvQgEgFgEgHIgGgMIAZAAIAGALIAJANg");
	this.shape_3.setTransform(-72.8,1.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.lf(["#D7D7D7","#FFFFFF"],[0,0.549],0,6.3,0,-7.4).s().p("AAmBEIgEgBIgEgDIgDgEIAAgEIAAggIgbAAQgGABgEgFIgEgFIgBgHIAAg+QAAgFAFgFIAEgDIAGAAIAxAAQAHAAAEADQAEAEAAAGIAABDIgBADIgDAFIgFACIgGABIAAAaIACADIACACIARAAIgFANgAAHAIIABACIACABIAcAAIACgBIACgCIAAgKIgjAAgAAHgPIAjAAIAAgMIgjAAgAAIg0IgBABIAAAKIAjAAIAAgJIgCgCIgCgCIgcAAIgCACgAgVBEQAGgHAFgLQAEgMACgHIAXAAQgCAJgEAKIgJASgAhFAzIAPgDIAAguIgLAAIAAgOIALAAIAAglIgPAAIAAgPIAyAAIAAAPIgNAAIAAAlIAJAAIAAAOIgJAAIAAAnIAPgFIAAAOIg0ARg");
	this.shape_4.setTransform(-88.7,1.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FCEF00").s().p("AgVAkIAMgIQAHgGACgFIAEgIIACgIIgVAAIAAgkIAlAAIAAAUQAAARgFAMQgFAOgMAIg");
	this.shape_5.setTransform(48.6,8.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FCEF00").s().p("AgdBaQgOgKgIgPQgFgKgDgMQgDgPAAgIIgBgiQABgSAEgPQADgKAEgKQAEgIAJgIQAIgGAJgEQAKgEAKAAQALAAAMAFQAMAFAIAIQAGAHAFAKQAEAJACAKQAEAPAAAPQABAOgBAQQgBAPgCAMQgDAOgHAMQgHANgNAHQgNAHgPABQgTAAgMgIgAgLhCQgHAHgCAOIgCAcIAAAyIACAMQABANAHAIQAGAHAGABQAHAAAFgGQAHgGACgNIACgMIgBhQQgEgPgFgGQgGgHgGgBIgBAAQgFAAgGAGg");
	this.shape_6.setTransform(89.7,-1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FCEF00").s().p("AgdBaQgOgJgIgQQgEgJgEgNIgDgXQgBgQABgSQABgSAEgPIAGgUQAFgJAIgHQAJgGAIgEQALgEAJAAQAMAAALAFQALAEAJAJQAHAJAEAIIAHATQADAQABAOIgBAeQAAAMgDAPQgDAPgHALQgIAOgMAGQgMAHgQABQgSAAgNgIgAgLhCQgGAHgDAOIgCA+IACAcQACAOAGAHQAGAHAGABQAHAAAGgGQAGgGADgNIABgMIAAhEIgBgMQgDgOgFgHQgGgHgHgBIgBAAQgGAAgFAGg");
	this.shape_7.setTransform(74.8,-1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FCEF00").s().p("AgdBaQgOgKgIgPQgFgKgDgMIgDgXQgBgTAAgPQABgSAEgPQADgKAEgKQAEgIAJgIQAJgGAIgEQALgEAJAAQAMAAALAFQAMAFAIAIQAGAHAFAKQAEAJACAKQAEAPAAAPQABAOgBAQQgBAPgCAMQgDAPgHALQgHANgNAHQgNAHgPABQgSAAgNgIgAgLhCQgHAHgCAOIgCAcIACA+QACAOAGAHQAGAHAGABQAHAAAGgGQAGgGACgNQACgEAAgIIABgQIgChAQgEgPgFgGQgFgHgHgBIgBAAQgFAAgGAGg");
	this.shape_8.setTransform(59.9,-1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FCEF00").s().p("AgVAkIAMgIQAHgGACgFIAEgIIACgIIgVAAIAAgkIAlAAIAAAUQAAARgFAMQgFAOgMAIg");
	this.shape_9.setTransform(48.6,8.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FCEF00").s().p("AgTBeQgLgCgJgGQgIgGgHgLQgFgIgCgIQgCgJgBgKIArAAIAAAPQABAHAEAHQAEAGAEACQAEADAFgBQAGAAAHgGQAGgHACgJQACgIAAgJQABgKgCgMQgBgKgDgDQgDgHgFgDQgGgCgFAAQgEAAgFADQgGAEgCAEIgEAHIgnAAIALhUQABgHAGgFQAEgEAHAAIBaAAIAAAXIhBAAIgCABIgCADIgFAnQAFgDAGgDIALgCIARABQAIACAIAGQAIAFAHAKQAGAKACAJQADALgBAMQAAAJgDAOQgEAMgHAKQgHAKgNAGQgOAFgLABIgIAAQgJAAgIgCg");
	this.shape_10.setTransform(37.8,-0.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FCEF00").s().p("AgCBLIAAgLIgKgBIgJgCIgJgGQgFgFgCgEQgGgLAAgMIAbAAIAAAHIACAHQABAFAEADQACACAFABIAAgmIgOgIQgIgCgGgHQgEgDgDgGQgDgFAAgGQAAgOAFgHIAHgGIAIgGIAJgCIAJgBIAAgLIAHAAIAAALQAMAAAHAFIAIAGIAFAHQAGAJAAAKIgbAAIgBgHIgCgHIgEgEIgEgEIAAAhIAUALIAIAGQAFAEACAFQAEAGAAAGQAAAGgBAHQgBAFgDAGQgFAGgEADQgGAEgGACIgNACIAAALgAAFAwIAFgBIAFgEQADgEAAgGIAAgHIgEgHIgEgEIgFgDgAgGgvIgDADQgGAEAAAHQgBACADAFQABADAEACIAGAEIAAgfg");
	this.shape_11.setTransform(24.2,1.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FCEF00").s().p("AAoBkIAAhsIgbAAIgEA4IgFAbQgDANgFAMIgjAAQAHgNADgLQAEgNACgNQACgOABgNIAAhYQAAgKAGgGQADgDAFgCIALgCQAUgBAZgDIAtgHIAAAVIgmAHIgmAEQgBAAAAAAQgBAAgBABQAAAAAAAAQgBAAAAABQgBAAAAABQAAAAgBAAQAAABAAABQAAAAAAABIAAAhIBXAAIAAAUIgcAAIAABsgAhdBkIgFgVIAQAAQAAAAABAAQAAAAABAAQAAAAAAgBQABAAAAAAQABgBAAAAQAAAAAAgBQABAAAAgBQAAAAAAgBIAAgrIgWAGIAAgWIAWgGIAAgxIgWAAIAAgVIAWAAIAAgmIAgAAIAAAmIASAAIAAAVIgSAAIAAAnIASgGIAAAUIgSAHIAAA9QAAAEgCAEQgBADgEADQgCACgEACIgIABg");
	this.shape_12.setTransform(7.8,-1.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FCEF00").s().p("AA4BjIgHgCQgDgBgDgDIgDgFIgCgHIAAguIgmAAQgKABgGgHIgEgGQgBgFAAgFIAAhbQAAgIAFgGQAEgDADgCIAIgBIBJAAQAJAAAGAGQAGAGgBAHIAABhIgBAHIgEAFIgHAEQgEADgFgCIAAAmQAAABABAAQAAABAAAAQAAABABAAQAAABAAAAQABAAAAABQABAAAAAAQABABAAAAQAAAAABAAIAYAAIgGAUgAAKAMIABADIADABIApAAIAEgBIABgEIAAgOIgyAAgAAKgXIAyAAIAAgQIgyAAgAALhMQAAAAAAAAQAAAAgBABQAAAAAAAAQAAABAAAAIAAAOIAyAAIAAgOQAAAAAAgBQAAAAAAAAQgBgBAAAAQAAAAAAAAQgBgBAAAAQAAAAAAgBQgBAAAAAAQgBAAgBAAIgoAAQgBAAAAAAQgBAAAAAAQgBABAAAAQAAAAgBABgAgfBjQAIgKAHgQQAGgMAEgRIAhAAQgCAOgGAPQgFAOgIAMgAhkBLIAUgGIAAhDIgQAAIAAgUIAQAAIAAg1IgUAAIAAgVIBIAAIAAAVIgTAAIAAA1IAOAAIAAAUIgOAAIAAA6IAVgIIAAAVIhKAYg");
	this.shape_13.setTransform(-15.8,-1.3);

	this.instance = new lib.C3_txt2_s();
	this.instance.parent = this;
	this.instance.setTransform(-103.5,-18.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.C3_txt2, new cjs.Rectangle(-103.5,-18.5,207,37), null);


(lib.C3_txt1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 圖層_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FEF9A0").s().p("AGcA3IAAgCIg0AAIgJgCQgEgBgCgDQgFgFABgJIAAgcQgBgEACgDIAEgFQAFgFAJAAIA0AAIAAgKIhSAAIAAgRIBSAAIAAgMIAhAAIAAAMIBSAAIAAARIhSAAIAAAKIA0AAQAJAAAGAFQAFAFAAAIIAAAcQAAAIgFAGQgGAFgKAAIgzAAIAAACgAG9AlIAiAAIAEgBQAAAAAAAAQAAgBABAAQAAAAAAgBQAAAAAAgBIAAgFIgnAAgAF1AhIACACQAAABAAAAQAAAAABABQAAAAAAAAQABAAAAAAIAjAAIAAgJIgnAAgAG9AMIAnAAIAAgGIgBgCIgDgBIgjAAgAF3AEQgBAAAAABQAAAAgBAAQAAAAAAABQAAAAAAAAIAAAGIAnAAIAAgJIgiAAIgDABgAEGA3IAAgFQAAgEgEgBIgSAAQABAEADAFIABABIgbAAIgFgKIgiAAIgEACIgBADIAAAFIgdAAIAAgJQAAgFAEgGQAEgDAHgBIAAgoQgBgHAFgFQAEgGAJAAIAUAAIADgHIguAAIAAgQICHAAIAAAQIg4AAIgEAHIAgAAQADAAAEACIAFAEIADAEIABAFIAAAqIAFACIAGAEQACAEAAAFIAAAKgAC/AfIA2AAIAAgIIg2AAgAC/AMIA2AAIAAgHIg2AAgADAgLQAAABAAAAQAAAAgBABQAAAAAAAAQAAABAAAAIAAADIA2AAIAAgDIgBgCIgCgCIgvAAgAC8A3IAAgDIAaAAIAAADgABnA3IAAgUIgRAAQAUgpAKguIAkAAIgLAoIgPAlIALAAIAAAegAAaA3IgKgXIAgAAIAJAXgAhQA3QAAgCADgDIAYgYIgSAAQgEAAgDgCQgCgBgBgDQgCgFAEgGIAWgZIhLAAIAAgUIBPAAIgHgQIAmAAIAEAIIADAIIBLAAIAAAUIhUAAIgVAZIAJAAIAJgJIAlAAIgfAgIAYAAQACAKAFAJIABAEgAgmAyIAUAAIgFgQgAiAA3IAKgXIAgAAIgHASIgCAFgAjQA3IAAhqIAgAAIAABqgAj5A3IAAhVIAcAAIAABVgAkhA3IgBgYIAcAAIACAYgAlKA3IAAglIgrAAIAAgTIArAAIAAgXIgmACIAAgVIA2gEQAkgDASgEIAAAWIgmAFIAAAaIAoAAIAAATIgoAAIAAAlgAluA3IABgYIAcAAIgBAYgAm3A3IAAgjIgBgNQgEgOgFgGQgFgHgHgBQgHgBgGAHQgHAHgCANIgCAyIgpAAIAAgTQABgPAEgSQADgIAEgKQAFgKAIgGQAIgHAJgDQALgFAIAAQANABAMAEQAMAFAHAIQAIAJADAIQAEAJADAJQAEAPAAAPIABASgAAMAXIAIgQIAHgPIAgAAIgGAPIgIAQgAh0AXQgJgQgGgQIAgAAQAFAQALAQg");
	this.shape.setTransform(55.3,-5.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FCEF00").s().p("AnvBeQgOgKgIgPQgGgNgCgIIgCgYIgBgiQAAgPAFgSQACgJAEgKQAGgKAIgGQAIgHAJgDQAKgFAJAAQANABALAEQAMAFAIAIQAIAJADAIQAEAJADAKQADAPABAPQAAAPAAAQQgCAOgCAMQgDAQgGAKQgIAOgNAGQgNAIgPAAQgTAAgNgIgAncg+QgHAHgCAOIgDAcIAAAyIACAMQADAOAFAHQAGAHAHABQAHAAAGgFQAGgGACgNIADgNIABgQIgDhAQgDgPgGgGQgFgHgHgBIgCAAQgFAAgFAGgAGPBkQgFAAgEgBIgGgGQgEgGAAgKIAAggIAgAAIAAAfQAAABAAAAQAAAAAAABQABAAAAABQAAAAABAAQAAABAAAAQABAAAAABQABAAAAAAQABAAAAAAIBCAAIgFATgADqBkIgPgHIgUAHIg9AAQAagJAbgMIgJgGIgFAEIglAAIAngsIAMAAIgEgEIgCgGIAAgSIAaAAIAAAOQAAAAABAAQAAABAAAAQAAAAAAABQABAAAAAAIADABIAkAAIgFAOIgkAAIgCAEIgDADIA4AAQAEABABACQAEABAAADIABAGQgBAEgCABIgMAKIgNAIIAuAVgADBA8IgCADIAWAAIAFADIAQgJIgmAAgABlBkIAAhvIgRAAQAUgqAJguIAkAAIgLAoIgOAmIALAAIAAB5gAg2BkIAAgkIhUAAIAAgVIBUAAIAAgOIAiAAIAAAOIBRAAIAAAVIhRAAIAAAkgAjqBkIgHgVIAaAAIADgBQAAAAAAAAQAAAAABgBQAAAAAAAAQAAgBAAAAIAAiuIAhAAIAAC1QAAAHgHAFQgEAFgJAAgAlMBkIAAiAIgrAAIAAgUIArAAIAAgXIgnACIAAgVIA2gEQAlgDARgEIAAAWIgmAFIAAAaIApAAIAAAUIgpAAIAACAgAHwBgQgHgMgDgKIgIgYIAhAAIAIAYIALAWgAFEBgIAJgWIAIgYIAgAAIgHAYQgDALgGALgAkcBTQgEgYgCgZIgDgxIAcAAQABARADAhQACAYAFAYgAl4BTIAFgzQADgYABgXIAcAAIgCAwQgCAXgEAbgAGvBJIgLgfIAhAAQAEAOAIARgAj7A0IAAiBIAcAAIAACBgAHpAqIgHgIQgnACgmABIhOABIAAgTIBSAAIAAgNIg0AAIgIgCQgEgBgCgDQgFgEAAgJIAAgcQAAgEABgEIAFgFQAFgFAIAAIA0AAIAAgKIhSAAIAAgRIBSAAIAAgMIAiAAIAAAMIBSAAIAAARIhSAAIAAAKIA0AAQAJAAAFAFQAGAFAAAJIAAAcQAAAIgGAFQgFAFgKAAIgzAAIAAAMIAcgCIgDgFIAmAAIAKAQQAEAHAIAIgAG7gJIAiAAIADgBQAAAAABAAQAAgBAAAAQAAAAAAgBQAAAAAAgBIAAgFIgmAAgAFzgNIABACQAAABABAAQAAAAAAABQAAAAABAAQAAAAAAAAIAjAAIAAgJIgmAAgAG7giIAmAAIAAgGIgBgCIgCgBIgjAAgAF0gqQAAAAgBABQAAAAAAAAQAAAAAAABQAAAAAAAAIAAAGIAmAAIAAgJIgiAAIgDABgAEGAlIgOgcIAMAAIAAgGQgBgDgEgBIgSAAQACADADAFIAFAIIgcAAIgJgQIgiAAIgDABIgBADIAAAHIAKAAIgQAbIgcAAIAOgWIgJAAIAAgPQAAgFADgGQAEgDAHgBIAAgpQAAgHAFgFQADgGAJAAIAUAAIAEgHIguAAIAAgQICHAAIAAAQIg5AAIgDAHIAfAAQAEAAADACIAGAEIACAEIABAFIAAArIAGACIAFAEQADAEAAAFIAAAPIgKAAQACAKAJANgAC9gPIA2AAIAAgIIg2AAgAC9giIA2AAIAAgHIg2AAgAC+g6QAAABgBAAQAAAAAAABQAAAAAAAAQAAABAAAAIAAADIA2AAIAAgDIgBgCIgDgCIgvAAgAgMAWIgDgHIgDgHIgFANIgxAAQgEAAgCgBIgEgGQgCgCABgDQABgEADgCIAXgXIgSAAQgEAAgCgCQgCgBgCgDQgBgFAEgGIAWgaIhLAAIAAgUIBOAAIgGgQIAmAAIADAIIAEAIIBKAAIAAAUIhTAAIgWAaIAJAAIAJgJIAlAAIgfAgIAZAAQACAKAEAIIAIASgAgpADIAUAAIgEgPgAAdAWIgQgkIAhAAQAGASAKASgAiJAWIAQgkIAhAAIgIARIgIATgAAKgXIAIgQIAGgQIAhAAIgHAQIgIAQgAh3gXQgIgQgGgRIAfAAQAFARALAQg");
	this.shape_1.setTransform(55.6,-0.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#D7D7D7","#FFFFFF"],[0,0.549],0,7.8,0,-7.2).s().p("AAnBFIgDgOIAJAAIACgBIABgDIAAgcIgOAAIgEAXIgFAXIgWAAIAAgCIABgDIgSAAIgKgZIAXAAIAHAVQAEgOABgPQACgQAAgPIAAg2IABgFIADgEIADgCIAGgBIAdAAIAHABIAEADQAEAGAAAEIAABqQAAAHgEADIgEAEIgGABgAAiAJIAOAAIAAgWIgOAAgAAjgzIgBACIAAAVIAOAAIAAgVIgBgCIgCgBIgJAAgAhFBFIAPgeIAWAAIgMAegAhCAiIAAgOIAJAAIAAg6IgIAAIAAgOIAIAAIAAgQIAWAAIAAAQIAQAAIAAgQIAVAAIAAAQIAGAAIAAAOIgGAAIAAA6IAHAAIAAAOgAgjAUIAQAAIAAgMIgQAAgAgjgEIAQAAIAAgKIgQAAgAgjgcIAQAAIAAgKIgQAAg");
	this.shape_2.setTransform(-10.8,2.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["#D7D7D7","#FFFFFF"],[0,0.549],0,7.5,0,-7.5).s().p("AgJBFQgJgCgGgEQgJgIgFgJQgEgKgCgLIAAgOIAAgQIABgRIADgNQADgJAFgHQAFgHAIgFQAHgEAJgBQAHgCAJACQAJACAFADQAHAEAEAHQAGAJABANIgdAAIgBgLIgDgFIgEgEQgFgDgFADQgDABgDADQgDAEgCAGIgCALIAAAMQAFgFAFgCQAFgCAHAAQAIAAAGACIALAIQAGAGAEAHQACAGABAKQABAJgCAJQgDALgEAFQgLAQgTADIgHAAIgJgBgAgFgCQgEACgCABQgDADgCAFIACAcIADAHIAEAFQADADADAAIAGAAQADgCADgDQADgDABgGIACgOIgBgOIgCgHIgFgEQgCgCgFgBg");
	this.shape_3.setTransform(-23.8,2.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.lf(["#D7D7D7","#FFFFFF"],[0,0.549],0,7.5,0,-7.5).s().p("AgCBGQgKAAgJgDQgHgCgFgGQgFgFgDgHQgDgFAAgGIgBgLIAeAAIABAOQAAAGAEAEQADADAEABQAFACAHgEIAEgFIADgHIAAgRIgBgHIgDgFQgCgCgEgBIgGgBIgQAAIAAgQIAQAAQADAAADgBQAEgCABgCQADgEABgIIAAgJIgBgHQgBgDgDgDQgDgCgDAAIgFAAQgEABgCACQgEAEAAAGIgCALIgeAAQAAgIACgGQACgHAFgFQAEgGAGgDQAGgDAGgCQAHgCAIAAQAIAAAIADQAOAEAHALIAEAKQABAGAAAFQgBALgHAIIgHAGIgJADIAIACIAHAEQAFAEACAGIACALQABAHgBAGQgBAGgDAHQgFAHgGAEQgGAEgIACQgIACgHAAIgDAAg");
	this.shape_4.setTransform(-34.3,2.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.lf(["#D7D7D7","#FFFFFF"],[0,0.549],0,7.4,0,-7.6).s().p("AgkBFIgFgOIAcAAIACgBIABgCIAAgLIg6AAIAAgMIA6AAIAAgDQAAgBAAgBQAAAAABgBQAAAAAAAAQABAAAAgBIAQgFIhBAAIAAgNIBnAAIAEABIACAEIAAADQAAABAAABQAAAAgBAAQAAABAAAAQgBAAgBAAIgjAOIA3AAIAAAMIg5AAIAAAPQgBAFgDAEIgEADIgGABgAgugCQgGAAgDgDQgDgEAAgGIAAgMQAAgFADgCIAEgDIAFgBIBcAAQAFAAAEAEQADAEAAAFIAAAMQAAAFgDADQgEADgFAAgAgigYIAAABIAAAGIAAACIACAAIA/AAIACAAIABgCIAAgGIgBgBIgCAAIg/AAgAhDgsIAAgOIA2AAIgFgKIAaAAIACAGIADAEIA2AAIAAAOg");
	this.shape_5.setTransform(-53.5,2.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.lf(["#D7D7D7","#FFFFFF"],[0,0.549],0,7.3,0,-7.7).s().p("AAHBEIAAh9IABgEIACgDQADgEAFAAIAlAAQAFAAADAEQAEADAAAEIAABeIgBAEIgDAEQgDADgFAAIgSAAIgEgOIAIAAIADgCIABgCIAAhQQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAAAgBAAIgLAAIgBABIgBACIAAB2gAgRBEIgEgNIgGAMIgYAAQgGAAgEgDQgCgCgBgDQgCgDAAgDIAAhtQAAgFADgDQADgDAGgBIArAAQAGAAAEAFQABADAAAEIAAA4IAAADIgCAEQgEADgFAAIggAAIAAAnIABADIACAAIASAAIgFggIAWAAIAFAZIAFAXgAgrgDIATAAIACgBIABgCIAAgQIgWAAgAgrg0IAAARIAWAAIAAgQIgBgCIgCgBIgRAAQAAAAgBAAQAAAAgBABQAAAAAAAAQAAABAAAAg");
	this.shape_6.setTransform(-69.6,2.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.lf(["#D7D7D7","#FFFFFF"],[0,0.549],0,7.3,0,-7.7).s().p("AgLBFIAAgSIg4AAIAAgOIA4AAIAAgKIglAAIgEgBIgFgDIgCgEIAAgFIAAgjQAAgFACgDIAEgDIAFgCIAlAAIAAgJIg2AAIAAgOIA2AAIAAgLIAWAAIAAALIA3AAIAAAOIg3AAIAAAJIAmAAQAEABAEAEQAEADAAAEIAAAnIgCAEQAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBAAIgDACIgEABIgmAAIAAAKIA5AAIAAAOIg5AAIAAASgAALAOIAYAAIACgBIABgDIAAgHIgbAAgAglAKIABADIACABIAXAAIAAgLIgaAAgAALgKIAbAAIAAgGIgBgDIgCgBIgYAAgAgkgTIgBADIAAAGIAaAAIAAgKIgXAAIgCABg");
	this.shape_7.setTransform(-85.5,2.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.lf(["#D7D7D7","#FFFFFF"],[0,0.549],0,7.4,0,-7.6).s().p("AAfBFIgEgNIAQAAIABAAIABgDIAAgGIglAAIAAAWIgSAAIAAgWIgHAAIAAgMIAHAAIAAgZQAAgHAEgDQAEgCAEAAIAOAAIAAgGIgfAAIAAgMIAOAAIAAgHIgLAAIAAgMIALAAIAAgHIgNAAIAAgNIANAAIAAgJIATAAIAAAJIAQAAIAAgJIAUAAIAAAJIAPAAIAAANIgPAAIAAAHIALAAIAAAMIgLAAIAAAHIAQAAIAAAMIghAAIAAAGIAPAAIAEABIAFACQADAEAAAFIAAAZIAHAAIAAAMIgHAAIAAANIgCAFQgCACgCABQgDABgEAAgAAlAjIAIAAIAAgHIgIAAgAAIAjIAIAAIAAgHIgIAAgAAlARIAIAAIAAgEIgBgCIgCAAIgFAAgAAIALIAAACIAAAEIAIAAIAAgGIgGAAgAASgUIAQAAIAAgHIgQAAgAASgnIAQAAIAAgHIgQAAgAgjBFIgFgfIASAAIAGAfgAhGBFIAFgPIADgQIATAAIgGAfgAg3AfQgFAAgDgCQgDgDAAgGIAAhLQAAgEACgDQAEgDAFAAIAaAAQAFAAADADQACADAAAFIAABLQAAAFgCACQgCADgGAAgAguAQIAAABIAGAAQAAAAABAAQAAAAAAAAQAAAAAAgBQABAAAAAAIAAgOIgIAAgAgugJIAIAAIAAgPIgIAAgAgugzIAAABIAAANIAIAAIAAgNQAAAAgBAAQAAgBAAAAQAAAAAAAAQgBAAAAAAIgEAAg");
	this.shape_8.setTransform(-101.5,2.5);

	this.instance = new lib.C3_txt1_s();
	this.instance.parent = this;
	this.instance.setTransform(-115.5,-17.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.C3_txt1, new cjs.Rectangle(-115.5,-17.5,231,35), null);


(lib.C3_MOTOR_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 圖層_1
	this.instance = new lib.C3_MOTOR();
	this.instance.parent = this;
	this.instance.setTransform(-59.5,-45);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.C3_MOTOR_1, new cjs.Rectangle(-59.5,-45,119,90), null);


(lib.C3_btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 圖層_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AkZBIIAOhMIgLAAQgDAXgGAQQgHAXgIAOIgWAAIAEgJIgNAAIAAgRIACgRIAQAAIgBAaQAEgJAFgPIAQhQQAAgEAEgEIADgCIAEgBIA1gLIgDAQIglAHIgCABIgBACIgFAaIAqAAIgDAPIgIAAIgPBMgAlvBIIAKgxIgYAAIADgPIAYAAIADgMIgbAAIADgPIAMAAIgCgTIAWAAIAAAKIABAJIAIAAIAJgTIAVAAIgDAKIgGAJIALAAIgDAPIgYAAIgDAMIAXAAIgEAPIgVAAIgJAxgACYBHIAPhOIgXAAIgBABIgBACIgMA5IgYAAIAMg+QAAgEAFgFIAEgDIAGgBIAlAAIADgSIg5AAIACgPIA6AAIgCgPIAaAAIABAPIA5AAIgDAPIg5AAIgDASIAlAAIAEABIAEADQAEAFgCAFIgJAwQgCAFgEAEIgFADIgGABIgaAAIgCgPIASAAIACAAIABgDIAIgnIgBgCIgBgBIgXAAIgPBOgAjQBHIgGgBIgEgDQgEgFABgHIAOhEIACgFIgKAAIArg0IAbAAIgJAMIA3AAQADAAADABQAAABABAAQAAABABAAQAAABAAAAQAAABABAAIAAAFIgCAHIgPARIAQAAQAHgBADAEQADADgBAGIgHAiQAAAFgEADIgGACIgFABIhbAAIgEAUIAAADIADABIBuAAIgIAOgAiJATIAZAAIADgCIABgCIAEgWIgBgCIgCAAIgZAAgAi3gJIgCACIgEAaIAcAAIAGgcIgaAAgAi0gYIAtAAIAQgRIAAgBIgBgBIgtAAgAhCBHIADgPIAtAAIAXh+IAZAAIgJAuIA+AAIgCAPIg/AAIgMBBIBGAAIgDAPgAmKBDIAIgTIAHgTIARAAQgDAMgDAHIgHATgAEuAaIBBgWIg4gUIAEgXIBQAiIgFAUIhdAigAlxgqIADgOIAXAAIgBgHIgBgHIAZAAIACAOIAWAAIgCAOg");
	this.shape.setTransform(0.1,0);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#11387A").s().p("AndBLIAjiVIOYAAIgjCVg");
	this.shape_1.setTransform(1.8,-7.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#061E47","#113274"],[0,1],0,15,0,-15).s().p("AnuCWIBGkrIOXAAIhGErg");
	this.shape_2.setTransform(0.1,0);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("An7CgIBLk/IOsAAIhLE/gAnuCWIOXAAIBGkrIuXAAg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.C3_btn, new cjs.Rectangle(-50.7,-16,101.6,32), null);


(lib.C2_usb = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 圖層_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhXBJQAHgRAEgPQAHgTACgNIAMg2IACgGIAFgFIAGgDIAIgBIApAAIAAgMIAdAAIABAMIAzAAIgDAPIhwAAIgEABIgCADIgLA2QgGAdgNAfgAg2BIIACgPIAvAAIADgOIgpAAIADgOIAoAAIACgJIgPAAIgBgJIAAgJIgJASIgVAAQAHgOAGgLIAMgcIATAAIgIAWIAJAAIABAMIABAMIAMg1IAXAAIgLA1QAFgJAHgNIAKgYIAVAAIgIAWIAHAAQAAAJACAGIACAQIgTAAIgBgPIgJAPIgTAAIgBAJIAnAAIgCAOIgpAAIgDAOIAvAAIgDAPg");
	this.shape.setTransform(33.5,0.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgQBIIgFgBIgEgDIgDgFIAAgEIACgHIglAAIgFgBIgEgEQgCgCgBgCQgBgDABgDIAGgYIACgFIAEgFQADgCACgBIAFAAIAmAAIABgGIAXAAIgCAGIAoAAIAFAAIADACIACAFIABAEIgGAbQgBAFgFAEQgDADgCABIgGABIgmAAIAAACQAAABAAAAQgBABABAAQAAAAAAABQAAAAAAAAQABAAAAABQAAAAAAAAQABAAAAAAQAAABABAAIA5AAIgHANgAAAAmIAZAAIACAAIACgDIABgEIgdAAgAgzAjIABACIACABIAZAAIABgHIgcAAgAADATIAdAAIABgEQABgBAAAAQAAAAAAAAQAAAAgBgBQAAAAAAAAIgCgCIgaAAgAgtANIgBACIgBAEIAcAAIABgIIgYAAgAARgHIACgLIAWAAIgCALgAgrgHIACgLIAYAAIgCALgAAvgKIAGgaIgBgCIgCgBIgiAAIgHAdIgWAAIAGgdIghAAIgCABIgCACIgFAaIgXAAIAGgbQABgGAFgDQAFgFAGgBIAtAAIACgGIgzAAIADgNIB9AAIgDANIg0AAIgCAGIAvAAQADAAACACIAEADQADAEgBAFIgGAcgAAUgXIACgLIAXAAIgCALgAgogXIADgLIAXAAIgCALg");
	this.shape_1.setTransform(17.9,0.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAMBJIgGgCIgEgEQgCgEAAgGIAKgtIgUAAQgBAHgEALIgHAPIgLAOIgQAOIglAAQALgHAKgIQAKgIAHgKQAGgHACgGQAEgIABgHIgSAAQgDgBgDgBIgDgEIAAgGQACgCADgDIAlgiIgnAAIAEgOIA7AAIgBgSIAbAAIAAAJIACAJIA3AAIgDAOIhJAAIgnAkIA/AAIgJgZIAbAAQAIAWAMASIgdAAIgHgMIgHALIAFAAIgJArIABACIACABIAkAAIgHAQg");
	this.shape_2.setTransform(0.9,0);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAtBJIgIgBQgDgBgDgDIgBgDIgCgDIgMAIIgdAAIAjgXQgEgNAAgQIgNAAIgDAKIALAAIAAAMIABALIgOAAIAAgIIAAgIIgIATQgFAMgGAHIgWAAIAQgbIALgcIgGAAIADgPIAHAAIABgCIAAgCIATAAIgBAEIAJAAIACgJIgIAAIgCgJIgEAIIgPAAIgEgBIgBgDIAAgEIACgEIAOgQIgFAAQgEAAgBgDIAAgDIABgEIASgZIASAAIgRAXIAGAAIAEABIACADQAAADgCADIgLALIAIAAIABAQIANg+IAUAAIgGAcIATgaIASAAIgRAXIAKAAIADABIACACIgBAEIgCADIgLALIAJAAIAAALQAAAFABAEIgLAAIAAgJIgFAIIgVAAIgBAGIAAAEIAGAAIAAgDIAAgDIAUAAIABAGIAHAAIgDAPIggAAIABAGIABAHIAGgHIAWAAIgKAMIgMALIABAEIACADQADAFAFAAIAHAAIgGAOgAAEgRIAGAAIAAgIgAA8gSIAHAAIAAgDIAAgEgAArgTIAPgPIgGAAIgEAAIgDgBgAhFBJIAXhrIgRAAIAEgPIAQAAIAFgXIAUAAIgFAXIAOAAIgDAPIgOAAIgXBrgAhTA1IAVhPIAKAAIgVBPgAgkAtIANhHIAIAAIgLBHg");
	this.shape_3.setTransform(-15.2,0);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgxBIIgCgPIATAAIAEgCIACgDIAGgZIg8AAIADgQIA8AAIAFgUIg0AAIADgQIA0AAIAFgXIg3ACIADgRIBDgBQAggDAmgFIgEAQIg4AGIgGAZIA0AAIgEAQIgzAAIgFAUIA7AAIgDAQIg7AAIgGAfQAAADgDADQgBADgDACIgGACIgGABg");
	this.shape_4.setTransform(-31,0);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgqA8QgFAAgEgDQgEgFACgHIAThZQABgEACgDQADgDADgBQAFgEAIAAIArAAQAIAAAFADQAFACADAFQAEAIgCAMQgCALgHAIQgIAHgLACIAJABQADAAAEADQADACABAFQACAEAAAGQAAAFgCAFQgBAGgDAEQgFAKgLAGQgJAEgMAAgAgbAqIABACIACABIAZAAQAGAAAEgDQAEgCADgHIACgGIABgHIgBgHQgBgDgCgCQgDgCgCAAIgGgBIgZAAgAgHgrIgCACIgGAgIAWAAQAGAAAGgDQAEgDACgGIACgHIAAgHQAAgEgCgCQgEgDgEAAIgVAAIgDABg");
	this.shape_5.setTransform(-45.3,0.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgPA9IgNgCQgGAAgGgFQgHgFgCgFIgCgEIgCgGIgBgGIABgGIAcAAIAAAIIACAHQACAFAEACQAFADAFAAQAGAAAEgBIAJgEQAEgEACgFQACgFgBgEQgBgEgEgDQgFgEgGgBIgMgDIgNgEQgFgCgFgEQgEgFgBgFQgCgGAAgFIAEgMIAHgLIAMgKIAOgEQAGgCAIAAIANABIAMADQAJADAFAJQACAEABAFIABAMIgcAAIAAgHQAAgEgCgDQgCgEgEgCQgGgCgEAAIgHACIgGADQgEADgCADQgCAFABAEQAAAEADADIAIADIAeAKQAHADAFAEQADADABAFQACAFgBAHQgCAJgDAGQgEAIgHAFIgHAGIgJADIgQADIgHABIgHgBg");
	this.shape_6.setTransform(-56,0.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgjA7QgGAAgFgEQgGgEgCgEQgEgGAAgGQgBgGACgIIARhRIAbAAIgTBVQgBAFABAEQABAEACACQAEAEADABIAJACQAGAAAEgCIAIgFIAGgGQADgFAAgEIAThVIAaAAIgSBRIgEANQgDAGgFAFQgLALgQADQgHACgLAAg");
	this.shape_7.setTransform(-66.7,0.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AqLB9IA2j5ITiAAIg3D5gAp/BzITNAAIAyjlIzNAAg");
	this.shape_8.setTransform(-15.1,0.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.lf(["#061E47","#113274"],[0,1],0,12,0,-12).s().p("AqFB4IA0jvITXAAIg0Dvg");
	this.shape_9.setTransform(-15.1,0.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AipBPIDbhWQgFgMABgJQAAgbASgRQASgTAaAAQAZAAASATQATARAAAbQAAAZgTASQgSASgZAAQghAAgSgcIjdBXgABIhAQgPAOAAAWQAAAUAPAOQAPAOAVAAQAUAAAPgOQAOgOAAgUQAAgWgOgOQgPgPgUAAQgVAAgPAPg");
	this.shape_10.setTransform(63.4,-8.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgUAVQgJgJAAgMQAAgLAJgJQAJgJALAAQANAAAIAJQAJAJAAALQAAAMgJAJQgJAJgMAAQgLAAgJgJg");
	this.shape_11.setTransform(74.1,-11.5);

	this.instance = new lib.usb_s();
	this.instance.parent = this;
	this.instance.setTransform(-84.5,-19.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.C2_usb, new cjs.Rectangle(-84.5,-19.5,169,39), null);


(lib.C2_MOTOR_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 圖層_1
	this.instance = new lib.C2_MOTOR();
	this.instance.parent = this;
	this.instance.setTransform(-56.5,-45);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.C2_MOTOR_1, new cjs.Rectangle(-56.5,-45,113,90), null);


(lib.C2_allview = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 圖層_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhXBJIAPgXIAJgUIAHgTQAEgLABgKIAOg9IAVAAIgUBVIAIAAIAAAWIACAVIANAAIgDgQIAXAAIACAIIABAIIAIAAQAGgHAFgJIAYAAIgKAQIATAAIgDAPIhdAAIABgHIgNAAIgBgUIgRAcgAgFAlQgGAAgDgEQgEgDACgIIADgQIADgFIAEgEIgXAAIALgkIADgMIANAAIgBADIAIAAIACAIIAIgNIAAgDIgCgBIgPAAIADgNIAcAAQAGAAACADQADAFgDAHIgGANQgCAFgFAHIAWAAIgDgUQgBgKAAgLIAVAAIABAKIAIgKIAOAAIgJAMIgLAMIABAFIADgEIADgDIAPAAQgHALgLAKQACAOAGALIgQAAQABABAAABQABAAAAABQAAAAAAAAQAAAAAAABIABAFIgEARQgCAHgEADQgEAEgGAAgAAIAJIgBABIgCAKIABACIABABIAdAAIACgBIADgMIgBgBIgBgCIgdAAgAAMgOIgGAJIAuAAIgBgCIAAgEIgBgDIgBgCIgjAAgAgOgHIALgQIgDgOgAhCgDIACgXIAFgZIALAAIgEAZIgDAXg");
	this.shape.setTransform(77.8,-6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AABBIQgFAAgEgFIgCgEIAAgGIADgNIgmABIADgOIAmgBIACgMIgeABIADgOIAdgBIADgKIgQABIgJAAIgIAAIADgOIBmgHIgDAOIguAFIgCAKIArgBIgDAOIgrABIgDAMIA1gCIgDAOIg1ACIgCAMIAAACIACABIAzAAIgIAOgAhVBIQAFgKAGgQIAHgbIARhLQAAgGAGgFQAFgEAIAAIBqAAQAGAAADAEQAEAEgCAEIgDASIgCAFIgEADQgEAEgFAAIhkAAIgLAzQgDAOgFALQgFAOgFALgAgag4IgBACIgCAKIBVAAIACAAIABgCIACgIIgBgCQAAAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAAAIhTAAg");
	this.shape_1.setTransform(61.2,-6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAKBIQgFAAgDgCIgDgGIgCgHIgBgHIgjATIgtAAIAngVQASgJASgMIgEgsIgwAAIAEgPIAqAAIgBgnIAZAAIABAnIBLAAIgDAPIhGAAIAEAdIAbgVIAhAAIgcAWIgdAVIACAKQAAAGADAEIACADIAFAAIAlAAIgIAPgAAugnIgNgdIAbAAIAPAdg");
	this.shape_2.setTransform(44.8,-6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgbBIIgKgCIgJgDIgHgFIgJALIgbAAQANgOAFgJQAIgLAGgOIABgCIgBAAIgJAAIgFgBIgCgDIAAgEIACgEIATgbQABAAAAgBQAAAAAAAAQAAAAAAAAQAAAAgBAAIAAgBIgPAAIADgPIAkAAQABAAABAAQAAAAABAAQAAABABAAQAAAAAAAAIADADQABAEgEAFIgTAbIAGAAQAFAAACADQACAEgCAEIgGAPIgIAPQAEADADABIAIADIAKACIBTABIgHAPgAArAvIgDg3IACgJIAag3IAWAAIgaA5IgBADIACA7gAALAvIgBg5IAAgEIACgEIAZg2IAWAAIgZA3IgCAGIACA6gAgTAvIgBg4IABgEIAAgEIAZg3IAWAAIgZA3IgCAEIAAAEIACA4gAgvgpIgFgQQgCgJAAgGIAaAAIADAQIAFAPg");
	this.shape_3.setTransform(29,-6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgbBJIAFgTIg8AAIADgPIA8AAIACgKIgnAAIgFgBQgCgBgBgDIgBgEIAAgGIAIglQAAgEAEgEQADgDADAAQACgBADAAIAnAAIACgLIg5AAIADgOIA4AAIADgLIAYAAIgDALIA6AAIgDAOIg5AAIgDALIAoAAQAFAAADAEQACAEAAAEIgJApIgCAEIgFADIgEADIgEABIgnAAIgDAKIA8AAIgDAPIg8AAIgDATgAAJAOIAZAAIACgBQABAAAAAAQAAAAABgBQAAAAAAAAQAAgBAAAAIACgIIgcAAgAgoALIAAACQAAAAAAABQAAAAAAAAQABAAAAAAQAAAAABAAIAYAAIADgLIgcAAgAAPgKIAcAAIABgHIAAgDQAAAAAAAAQAAAAgBgBQAAAAAAAAQgBAAAAAAIgZAAgAghgUIgCADIgBAHIAbAAIADgLIgYAAg");
	this.shape_4.setTransform(12.8,-6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAUBKQgJgIgFgIIgjAAIgKAJIgLAHIghAAIAYgQIgDgCIgCgCQgCgEABgHIAEgTIgPAAIAdgYIgWAAIADgMIAkAAIABgFIgdAAIACgLIAdAAIABgFIgNAAIgBACIgWAAIAEgUIACgGIAEgDIAFgDIAGgBIAtAAIgCgJIAbAAIACAJIArAAQAGABADAEQACAEgBAFIgEATIgXAAIAAgCIgNAAIgBAFIAcAAIgCALIgcAAIgBAFIAkAAIgDAMIgVAAIAIANIAJALIgPAAIgHAbIgCAEQgEACgDABIAPAQgAgpAtIAAACIACABIA8AAIADgBIABgCIABgDIhCAAgAgnAiIBCAAIACgFIhCAAgAgiAQIgBACIgBADIBCAAIABgEIAAgBIgBgBIg+AAgAgXADIgCACIA0AAIgDgFIgsAAgAgHgMIAYAAIABgFIgYAAgAgEgcIAYAAIABgFIgYAAgAAvgsIANAAIAAgEIAAgCIgCAAIgKAAgAAAgsIAYAAIABgGIgZAAgAgjgyIgBACIgBAEIAOAAIABgGIgLAAg");
	this.shape_5.setTransform(-3.6,-6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AArBJIgKgBQgDAAgDgDQgCgCgCgDQgBgDAAgGIAAgqIAEgrIhYAAIADgPIBWAAIACgbIAZAAIgDAbIAgAAIgDAPIgfAAIgDBTQAAABAAABQAAAAAAABQABAAAAAAQAAABAAAAIAFABIAMAAIgIAPgAhQA1IAQgBIAQgBIAKgvIgcAAIAEgOIBRAAIgEAOIgcAAIgJAsIAjgFIgDAQIhdAKgAA9gyQgCgKAAgLIAXAAIACAVg");
	this.shape_6.setTransform(-19.9,-6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgiBIIAAgOIAOAAIACAAIACgDIADgOIgnAAQgEAAgEgEQgCgDABgFIADgNQAAgEAFgDIAEgCIAFAAIBlAAQAFgBACADQADADgBAGIgCALQgCAGgDACIgEADIgFABIgoAAIgEATQgBAGgEADQgEADgGAAgAgiAUIgBABIgBAFIAAABIABAAIBJAAIABAAIABgBIABgEIAAgCIgCgBIhIAAgAAkBGQgLgLgFgNIAcAAQADAHAGAHQAGAFAGAFgAhVBGIARgLQAJgHAFgGIAcAAQgGAHgJAHIgOAKgAhBAAIADgMIA9AAIgBgIIgmAAIgGgBIgDgEQgCgEABgFIAFgZQACgFADgDQAEgEAHAAIBoAAQAGAAADADQACAEgBAFIgGAbQgBAGgEACQgEAEgFAAIgrAAIACAIIA7AAIgDAMgAgZgkIAAABQAAABABAAQAAAAAAAAQAAAAAAAAQABAAAAAAIBMAAIACAAIABgCIABgEIhRAAgAgUg5IgBABIgBAEIBRAAIABgDIAAgCIgCgBIhNAAg");
	this.shape_7.setTransform(-36.7,-5.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AhRBIIADgQIA5AAIAFgXIgmAAIADgQIAmAAIAFgUIgsAAIABgHIgWAAIAcgWQAMgKAOgOIgWAAIAEgPIBDAAIAFABIAGABIAEADQABABABAAQAAAAAAABQABAAAAABQAAAAAAABIAiA0IgUAAIgCAHIgrAAIgFAUIAmAAIgEAQIgmAAIgFAXIA5AAIgEAQgAgVgaIgKAIIBMAAIgLgRQgGgHgEgJIgEgEIgFgBIgGAAg");
	this.shape_8.setTransform(-52.5,-6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AscB9IA2j5IYEAAIg3D5gAsQBzIXvAAIAyjlI3vAAg");
	this.shape_9.setTransform(12.9,-6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.lf(["#061E47","#113274"],[0,1],0,12,0,-12).s().p("AsWB4IA0jvIX5AAIg0Dvg");
	this.shape_10.setTransform(12.9,-6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AiCBoQgRgOgFgUQgGgZAMgWQANgWAZgGQAIgBAIAAQATAAAPAJQAQAKAHASIC1iSIAJALIi6CVQADAWgLATQgNAWgZAGIgPACQgVAAgRgMgAhpAGQgUAFgKASQgLASAFAUQAFARAOAKQANAKARAAQAHAAAFgBQAUgGALgRQALgSgGgUIgBgDIAAAAQgFgQgNgJQgNgKgQAAIgNACg");
	this.shape_11.setTransform(-77.6,2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgOAaQgLgGgDgMQgDgMAGgKQAGgLAMgDQALgDALAGQALAGADANQADALgGAKQgHALgMADIgHABQgHAAgHgEg");
	this.shape_12.setTransform(-86.9,7.4);

	this.instance = new lib.allview_s();
	this.instance.parent = this;
	this.instance.setTransform(-97,-20.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.C2_allview, new cjs.Rectangle(-97,-20.5,194,41), null);


(lib.C2_4v = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 圖層_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgxBJIgDgNIAYAAIACAAIACgDIAAgEIg8AAIACgMIA+AAIABgKIgwAAIACgMIAxAAIABgGIg3AAIADgLICFgFIgDAKIg2AFIgCAHIAxAAIgDAMIgwAAIgDAKIA8AAIgCAMIg8AAIAAAEQgCAHgEAEQgEAFgJAAgAgVgDIgBgHIgEAEIgEABIgcAAQgDAAgCgDQgBgCAAgDIADgMIgJAAIARgXIAEAAIABgGIgOAAIADgLIANAAIACgHIAVAAIgCAHIANAAIACgHIAUAAIgCAHIAMAAIgCALIgMAAIgBAHIgVAAIABgHIgMAAIgBAHIgFAAIgBACIgBACIAjAAQAGAAACAEQACACgBAGIgCAPQgCAFgFAEQgCAEgHAAgAgtgTIgBABIAAACIAAABIABABIAGAAIABgBIABgBIAAgCQAAgBAAAAQAAAAAAAAQAAgBAAAAQgBAAAAAAIgGAAgAgsgfIgBACIATAAQAEAAACADQABADAAADIAAADIACAAIABgBIABgCIADgKIgBgCIgCgBIgbAAgAABgEIAZgQIgLgPIAcAAIAKgOIgLAAIgEAFIgEAEIgXAAIAXggIAVAAIgEAJIAiAAIgDAOIgHAAQgEAHgFAHIgMANIAXAQIghAAIgCgCIgCgBIgHAFg");
	this.shape.setTransform(84.8,-2.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAWBIIAfiPIAZAAIggCPgAhLBIIgCgPIAtAAIACgBIABgCIAHgeIAAgCIgCgBIgpAAQgEAAgCgBIgEgDQgCgEABgHIAIgYQABgFAGgEQAFgDAFAAIAmAAIACgBIABgDIAEgQQAAgBAAAAQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAAAgBAAQAAgBAAAAQAAAAgBAAQAAAAgBAAIg4AAIADgPIBGAAIAGABIAEADQACAFgBAEIgGAcIgCAFIgEAEQgEAEgGAAIgoAAIgBABIgBACIgFAPQAAAAAAAAQAAABAAAAQAAAAAAABQABAAAAAAIACABIAoAAQAEAAACABIACAEIACAEIAAAFIgHAmQgBAFgFAFQgFAEgIAAg");
	this.shape_1.setTransform(69,-2.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAFBJIgBgPIAZAAIACgBQAAAAAAAAQAAAAABgBQAAAAAAAAQAAgBAAAAIAShVIgoAAIADgOIAoAAIAGgbIAZAAIgHAbIAMAAIgDAOIgLAAIgUBYQgBAHgFADQgFAFgHAAgAgxBJIgCgPIAOAAIABgBIABgCIAFgSIgVAVIgHAGIgeAAIAZgTIAUgSIgfAAIADgPIAHAAIANg4IABgFIADgDIAFgEIAFgCIAHAAIAIgOIAXAAIgDAIIgEAGIAEAAQAFAAAEADQADADgBAIIgJAoIAKAAIgMAOIgKAwQgCAHgEADIgFAEIgGABgAgpAMIAQAAIACgKIgQAAgAgkgKIAQAAIACgKIgQAAgAgdgqIgBABIgBAHIAQAAIACgHIgBgCIgBAAIgMAAgAANAmIgCgaQAAgMACgOIATAAQgCAZACAbg");
	this.shape_2.setTransform(51.7,-2.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAgBJIgJgTIAbAAIALATgAgmBJIAUgTIAcAAIgSATgAhFBAIgFgBQgBAAAAAAQgBgBAAAAQgBAAAAgBQAAAAgBgBIgCgFIABgGIAVhjQACgHAEgDQADgDAGAAIAXAAQAHAAACAEQADAFgCAFIgVBjQgCAGgDAEQgEAEgHAAgAgmgvIgBACIgUBbIAAACIACABIAFAAIACgDIAUhbQAAgBAAAAQAAgBAAAAQAAAAgBAAQAAgBgBAAIgEAAgAgIAyIgFgBIgEgCQgEgFABgGIAIgjIACgFIADgEIAEgCIADgDIABgHIgOAAIADgOIAOAAIACgIIATAAIACgGIgdAAIACgOIAeAAIACgJIAWAAIgCAJIAdAAIgDAOIgdAAIgBAGIAUAAIgCAIIAPAAIgDAOIgPAAIgBAIQAEABACAEQACADgBAFIgHAhQgDAIgDAEQgFAEgIAAgAACAjQAAABgBAAQAAABABAAQAAAAAAAAQAAAAABAAIAiAAIABAAIABgCIABgEIgmAAgAAEAVIAmAAIABgGIglAAgAAKAAIgBACIgBACIAmAAIAAgCIAAgCIgCAAIggAAgAAWgNIASAAIACgHIgTAAgAAagiIASAAIACgFIgSAAg");
	this.shape_3.setTransform(35.7,-2.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgFBIIgBgNIAcAAQAAAAABAAQAAAAABgBQAAAAAAAAQABgBAAgBIABgDIhPAAIgEATIgYAAIALgzQACgGAFgEQAEgDAGAAIBhAAQAIAAADAFQACADgBAHIgIAkQgBAGgEADQgGAEgFAAgAgzAqIBPAAIABgFIhPAAgAguAWIgBACIAAACIBOAAIABgCIAAgCIgCgBIhKAAgAAlAEIgFgDIgEACIgEABIgiAAIADgBIADgBIgQAAIgCgFIAAgHIgEAAIgJAMIgRAAIAJgMIgGAAIgHAMIgVAAQAEgFAEgIQADgIADgLIAGgdQACgGAEgEQADgCAHAAIAtAAQAFAAACACQACADAAAFIgEAOIgCADQgDACgEAAIgBAGIAGAAIgCALIgGAAIgBAFIAIAAIgDAKIgGAAIACALIAWgJIgMgMIAZAAIAEACIAFgCIAEgEIglAAIACgKIA2AAQABAAABAAQAAAAABABQAAAAABAAQAAAAABABQAAAAAAABQABAAAAAAQAAABAAAAQAAABAAAAQAAAFgEAEIgRAMIALAHIALAFgAgZgUIAGAAIABgFIgGAAgAgugUIAGAAIABgFIgGAAgAgWgkIAHAAIABgGIgHAAgAgqgkIAGAAIABgGIgGAAgAglg7IgBAFIAcAAIACAAIAAgBIABgDQAAgBAAAAQAAAAAAAAQAAgBgBAAQAAAAAAAAIgbAAgAA2gmQgDAAgCgDQgCgDABgDIACgKIgBgCIgBAAIgGAAIgCAAIgBACIgDALQgCAFgEADIgWAAQAFgEACgHIAEgNQACgFAEgCQACgCAGAAIAeAAIAEAAIADADQACADgBAEIgCAJQAAAAAAAAQAAABAAAAQAAAAAAABQAAAAAAAAIACABIALAAIgFALg");
	this.shape_4.setTransform(19.8,-2.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgXBIQgGAAgDgDQgDgEACgGIAEgSIAXAAIgDAOIABACIACABIAGAAIAFgXIglAAIADgPIAlAAIADgNIgFAAIgHAIIgbAAIAZgZIgWAAIATgJIgEgIIgCgKIAUAAIAEAKIADgCIADgBIgDgHIgCgGIgBACIgCABIgYAAIgCALIgMAAIgGAbIAFgCIAGgDIgEAQIgLAFIgJAsIgDAGIgEAFQgFADgGAAIgPAAIgCgOIAJAAIACgBIACgDIAGgfIgGACIgHACIADgQIAHgCIAHgDIAIgjIgNAAIAEgQIAMAAIAGgbIAXAAIgGAbIAMAAIAbgbIAbAAIgDAFIgDADIAnAAQADAAADABQADADAAACIgBAGIgEAFQgQANgMAGQgJAHgYAKIAGAAIgBACIgCACIAzAAIgDAOIghAAIgDANIAmAAIgDAPIgmAAIgFAXIAIAAIACgBIABgDIADgNIAXAAIgEATQgCAGgDADQgFADgGAAgAAPgtIATAAIABADIABACIAPgJIABAAIgBgBIgeAAg");
	this.shape_5.setTransform(3.1,-2.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAOBJIAQhJIgYAAIAEgQIAXAAIAMg4IAZAAIgMA4IAYAAIgDAQIgYAAIgQBJgAhOA5IAZgCIAJgtIgXAAIADgNIAYAAIADgQIgQAAIACgJIgKAAIAWgjQACgFAFgCIAHAAIAZAAIADAAIAEADQADADAAAEIABAQIACAQIgMAAIgBAJIgOAAIgDAQIAUAAIgDANIgUAAIgJArIAYgDIgDAOIgkAFIglADgAgTg3IgCABIgMAUIAWAAIgBgUIgBgCIgBgBIgDAAgAhGAwIADgeIAQAAIgEAegAgYAtIAJgbIAOAAIgJAbg");
	this.shape_6.setTransform(-13.6,-2.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgTBJIgFgCQAAAAgBAAQAAAAgBgBQAAAAgBgBQAAAAAAgBQgDgDABgGIACgLIgSAAIAJgHIAWgWQgEAAgFgDIgCgFQgBgCABgDIAGgXIgLAAQALgGAHgHIANgOIgXAAIAEgPIAmAAIgCgNIAaAAIADANIApAAIgEAPIgVAAIgBAJIAAACIABABIAUAAIgGAOIgHAAIgFAXQAAAEgDAEIgGAEQgDACgDAAIgjAAIgPARIgEATIABACIABABIAWAAIgIAPgAADgKIgBACIgCAKIAAACIACAAIAlAAIACAAIABgCIACgKIAAgCIgBAAIglAAgAATgiIgKAJIAcAAIAAgDIADgQIgNAAgAAgBIQgJgMgEgJQgGgLgEgOIAaAAIAEAJQAGgEAFgIIAXAAIgZAeIAHALIAJAIgAhXBIQAPgZALgfIAZAAIgLAcQgFAMgIAQgAg8AHIgDgkIAZAAIADAkgAgyglIgCgRIgBgRIAaAAIADAig");
	this.shape_7.setTransform(-29.6,-2.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgmA8IgVh3IAdAAIAMBVIAxhVIAdAAIhIB3g");
	this.shape_8.setTransform(-42.4,-2.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgFA9IAFgbIgjAAQgDAAgCgBQgCgCgBgCQgBgEAEgGIA+hKQADgDAEgCIAIAAQADABADADQACACgBAFIgPBEIAMAAIgDAPIgMAAIgGAbgAgVATIAYAAIAJgmg");
	this.shape_9.setTransform(-54.7,-2.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("As6B9IA2j5IY/AAIg2D5gAsuBzIYrAAIAyjlI4rAAg");
	this.shape_10.setTransform(17.1,-2.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.lf(["#061E47","#113274"],[0,1],0,12,0,-12).s().p("As0B4IA0jvIY1AAIg0Dvg");
	this.shape_11.setTransform(17.1,-2.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AiKA+QgZgDgQgUQgQgVADgYQACgXASgQQASgQAXAAIAIAAQAVADAPAPQAPAPADAVIEGAAIAAANIkGAAIAAABQgCAYgSAPQgSAQgXAAgAikgkQgOAMgCATQgCAUAMAQQANARAVACIAGAAQATAAAOgMQAOgNACgTQADgUgNgQQgNgQgVgDIgGAAQgTAAgOANg");
	this.shape_12.setTransform(-80.5,-3.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgCAeQgNgCgHgJQgIgKABgLQACgNAJgHQAKgIALABQANACAHAJQAIAKgBALQgCANgJAHQgIAHgKAAIgDAAg");
	this.shape_13.setTransform(-93.6,-3.1);

	this.instance = new lib._4v_s();
	this.instance.parent = this;
	this.instance.setTransform(-104,-16.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.C2_4v, new cjs.Rectangle(-104,-16.5,208,33), null);


(lib.C1_txt2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 圖層_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FEF9A0").s().p("AUTA6IAPggQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBQAAAAgBAAQAAgBAAAAQgBAAgBAAIgkAAIgOAXIAeAAIgEAQIhRAAQAQgYAOgZIAeg7IArAAIgTApIAzAAQANAAAEAIQAEAGgEANIgLAdIgEALgAPUA6IABgFIgBgFQAAgBgBAAQAAAAgBgBQAAAAgBAAQAAAAgBAAIguAAIgEAMIgvAAIAEgMIguAAIgFACIgDAFIgCAFIgtAAIAEgPQADgJAHgHIAKgHQAEgCAGAAIBLAAIAFgSIhtAAIAJgcIBsAAIAHgWIAvAAIgHAWIBuAAIgIAcIhtAAIgGASIBKAAQALAAAFAIQAEAGgDAJIgEARgAK5A6QAIgGADgJIAHgSIAFgSQACgLgFgIQgCgDgEgDQgFgCgFAAIg2AAQgDAAgEADQgDACgBADIgVBGIg3AAIAWhNQADgJAGgHQAIgIAHgDQAOgIAQAAIBSAAQATAAANAEQAPAEAGAKQALAPgFAdQgBAKgEAOQgFAOgGAKIgBACgAEuA6IAJgVQAJgQAGgIIARgTQAJgKALgIQAMgJAKgFQAKgGANgEQASgGATgCQAUgCARADQARADALAGQAMAGAKAKQAKAOACAOQADAOgCARIg+AAQADgJAAgLQgBgLgCgDQgBgEgGgHQgEgFgIgBQgJgCgLABQgKACgJAEQgOAHgLAKQgMAKgIAMQgLAQgHARIgBADgADXA6IAAgaIAVAAQAAAAABAAQAAAAABAAQAAgBABAAQABAAAAgBQACgBABgDIALgmIAAgEQAAgBgBAAQAAAAgBgBQAAAAgBAAQAAAAgBAAIgVAAQgFASgJATIgOAVQgFAJgJAJIgwAAIAQgRQAJgNAEgIQAKgSAGgUIgYAAIAIgeIBxAAQAGAAAFADQAFADACADQAFAIgEAMIgQA1QgDANgLAHIgHAEgAACA6IADgMIAzAAIAKgiIgtAAIAJgcIAtAAIAKgjIAsAAIgKAjIAiAAIgJAcIgiAAIgKAiIAmAAIgDAMgAkiA6IAEgNIAqAAIgEANgAnIA6IAEgKQAEgMAJgFQAIgGAKAAIATAAIAFgBQACgCABgDIAKgfQAAgBAAAAQAAgBAAAAQAAgBAAAAQgBgBAAAAQgBgBAAAAQgBgBAAAAQgBAAAAAAQAAAAgBAAIgyAAIAIgdIBNAAQAJAAAGAGIACAHQABAEgCAGIgRA4QgBAJgJAHQgJAHgKAAIgVAAQgDAAgCACIgBABgAu0A6IACgFIheAAIAIgcIBeAAIAGgVIhpAAIAJgcIBpAAIAIgaIAvAAIgHAaIBpAAIgIAcIhqAAIgFAVIBdAAIgIAcIheAAIgBAFgAx0A6IAEgOQAAgBAAAAQAAAAAAgBQAAAAAAAAQAAgBgBAAIgCAAIgQAFIgDAMIh9AAIABgDIARgFIAUhDIAtAAIgQA1IAVgGIAYhQIAtAAIgUBBIAmgKQAFgBAFABQAEABADADQAGAGgCAKIgKAhgA0/A6IAGgVIgWAAIAJgdIAWAAIARg6IAuAAIgSA6IATAAIgIAdIgTAAIgGAVgAQ6AyIAIgbIArAAIAGgXIgzAAIAHgbIA0AAIAHgXIAtAAIgHAXIAvAAIgHAbIgwAAIgGAXIAmAAIgIAbgArFAvQgNAAgFgIIgCgIIABgJIANgsQADgKAKgIQAJgIAKAAIC+AAQANAAAFAIQAGAHgFAOIgLAoQgEAMgJAGQgJAIgLAAgAqoARQAAABAAAAQAAABAAAAQAAAAAAABQABAAAAABQAAAAABAAQAAABAAAAQAAAAABAAQAAAAAAAAICMAAQABAAAAAAQABAAAAAAQABAAAAgBQABAAAAAAIADgDIACgIIiWAAgAqdgSIgCAHICVAAIADgHIgBgDQAAAAgBgBQAAAAgBAAQAAgBgBAAQAAAAgBAAIiLAAQgEAAgCAFgAjjAlIgCgZIgRAXIhOAAQgKAAgEgHQgCgEABgGQACgGAFgFIAzg6IA1AAIg2A6IA0AAIAAgiIAtAAQAAAQABAQQACASAEAOg");
	this.shape.setTransform(2.5,-8.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FCEF00").s().p("AT/COQgGgTAAgRQgCgWACgSQgWAoghAkIgzAAIAWgXIgVAAQAAgNACgMQACgNACgNIAhAAQgEASgBAQQAUgaAPgeQAPgeALgeIgkAAIgIAYIh6AAIAJgbIB3AAQATgbARgeIAeg8IArAAIgTApIAyAAQAOAAADAIQAEAHgEANIgKAdQgEALgLARIgpAAIAWgxQABgBAAAAQAAgBAAAAQAAgBAAAAQAAgBgBAAQAAgBAAgBQAAAAAAAAQAAgBgBAAQAAAAgBAAIgkAAIgPAXIAfAAIgLAiIgNAgIAaAAQgBAbABAhQAAAbAIAegANWCOIALgkIhxAAIAIgcIBxAAIAGgUIhKAAQgEAAgEgCQgFgCgDgFQgBgDAAgFIABgKIAWhHQADgJAHgHIAKgHQAEgCAGAAIBKAAIAGgTIhtAAIAJgcIBsAAIAGgWIAwAAIgHAWIBtAAIgIAcIhtAAIgGATIBLAAQALAAAEAIQAFAGgDAJIgYBPQgBAFgDADIgIAHIgIAFIgJABIhMAAIgFAUIByAAIgIAcIhyAAIgLAkgAOmAfIAuAAQAEAAABgCIAEgFIAFgQIg2AAgANFAYQAAABAAAAQAAABAAAAQAAABAAABQAAAAABABQAAAAAAAAQAAABABAAQAAAAABAAQAAABABAAIAuAAIAHgXIg0AAgAO0gRIA2AAIADgNIgBgFQAAgBAAAAQgBAAAAgBQgBAAAAAAQgBAAAAAAIgvAAgANZgjIgEAFIgDANIA0AAIAFgUIguAAIgEACgAj7COQgBgEABgFQglAEgcABQgfADghAAIAIgbIBCgDIAKgiIgfAAQgMAAgFgHQgGgHAFgOIAMgrQAFgLAJgGQAJgGAKAAIAgAAIAGgVIAqAAIgGAVIAfAAQAMAAAGAHIACAHIgBAJIgOAsQgDANgJAIQgKAGgNAAIgdAAIgJAeQAJAAAFgCIACgTIArAAIgDAcQgBAQABAMgAj2AxIAKAAQADAAADgBIACgEIAIgeQABAAAAgBQAAAAAAgBQAAAAAAgBQgBAAAAAAQAAgBgBAAQAAAAgBgBQAAAAgBAAQAAAAAAAAIgLAAgAkkALQAAAAgBAAQAAABAAAAQgBABAAAAQAAABAAAAIgJAeQAAAAAAABQAAAAAAAAQAAABAAAAQABABAAABQAAAAABAAQAAABAAAAQAAAAABAAQAAAAAAAAIAMAAIAMgoIgMAAgAtkCOQgJgHgJgMQgHgHgMgSQgHgMgJgSQgGgPgEgMIA2AAIAFAPQAEAJAEAFIAjgiIAyAAQgDAGgLALIgPAQIgiAeQAIAMAKAKQAMALAOAKgAv5CNQgLAAgGgHQgFgIADgMIAJgfIg0AAIBTguIAagSIhPAAIAIgbIBxAAIAGgWIhdAAIAIgcIBeAAIAGgVIhpAAIAJgdIBpAAIAHgaIAwAAIgHAaIBpAAIgIAdIhqAAIgGAVIBeAAIgIAcIhfAAIgFAWIByAAIgJAbIiKAAQgLALgRAMQgSANgNAHIgNAtQgCAEADABQADACADAAIBHAAIgQAcgARDCNIgEgWIgDAGIglAAIAeg5IAjAAQgKAagMAUIAMAAIADgCIADgEIAQg2Ig0AAIAHgcICSAAIgIAcIgwAAIgTA+QgCAGgCAEIgIAIIgKAFQgFACgFAAgACFCNQgSAAgPgCQgPgCgRgGQgNgGgJgGQgKgHgHgKQgFAMgEAHIgLATIgiAAQARgdALgfQAKgcAKgmIAiAAIgQA2QABAGAGADIAZhUIg0AAIAJgeIAzAAIAKgiIgtAAIAJgdIAtAAIAKgjIArAAIgKAjIAiAAIgJAdIgiAAIgKAiIAnAAIgIAeIgoAAIgLAkIAmAAIgIAdIgmAAIgNAsIAZAHQANAEANAAICEAAIgQAcgAqpCNIAHgXIhNAGIgYABIAIgaIAIgBIAJgBIAchgIgQAAIAHgZIEUAAIgIAZIiGAAIgZBWIAIAAIAHgBIgIAbIgPABIgIAbgArBBdIAJAAIAegDIAFgPIgmAAgAq1A0IAmAAIAEgOIglAAgAqpAOIAlAAIAEgNIgmAAgAzpCNQgJAAgFgDQgEgCgFgEQgGgKAEgOIAhhvIgRAEIAJgdIARgFIAUhEIAtAAIgRA2IAVgGIAYhRIAtAAIgTBCIAlgKQAFgBAFABQAFABADADQAFAGgCAKIgfBpQgDALgKAHQgDADgIACQgFACgHAAIgXAAIgCgZIgNAuIgtAAIAih0IgVAGIgkB4QAAADABAEQADACADAAIB9AAIgTAdgAxqglIgYBRIANAAIAEgCIACgDIAYhOQAAgBAAAAQAAAAAAgBQAAAAgBAAQAAgBAAAAIgCAAgAnPCMIABgcIAiAAQAEAAACgCQACgCACgEIAQg3QAAgDgBgCQgCgCgEAAIgYAAQgIAAgEgHQgDgEAAgEQgBgFADgEIATg1QAEgMAIgFQAJgGAJAAIATAAIAFgBQADgCAAgDIAKggQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBgBAAQAAgBgBAAQAAgBgBAAQAAAAgBAAQAAAAAAAAIgzAAIAIgdIBOAAQAJAAAFAGIADAHQAAAEgBAGIgRA5QgCAJgIAHQgKAHgKAAIgVAAQgCAAgCACIgEAEIgKAeQAAABAAAAQAAABAAABQAAAAABAAQAAABAAAAIAEACIAVAAQAHAAAEACQAEABACAEQAEAHgEAMIgVBIQgEAMgJAIQgGAEgGACQgHACgIAAgAolCMIgOgQIgXAQIgyAAIA2grIgMgUQgFgKgDgMIAvAAIACAGIAEAGIATgUIABgDQAAgBAAAAQgBAAAAgBQAAAAgBAAQAAAAgBAAIhDAAIAIgaIBeAAQAHAAAFADQAEADACAEQABAGgDAGQgBAFgHAJIgUAWIgXAWIAkAsgAFuB9QgWgGgOgOQgOgOgEgTQgEgVACgUQACgMAEgMQACgLAGgPIAMgbQAIgQAGgIIARgUQAJgKAMgIQAMgJAKgFQAJgGAOgEQASgGATgCQAUgCARADQARADALAGQAMAGAJAKQAKAOADAOQACAPgBARIg+AAQACgJAAgLQgBgMgBgDQgCgEgGgHQgDgFgIgBQgJgCgLABQgKACgKAEQgOAHgKAKQgMALgJAMQgKAQgIARQgGAPgFATQgFASgBARQgBARAFAOQAFAKAKAGQALAHAMAAQAKAAAOgEQANgFAKgKQAJgIAGgKQAIgLADgJIA/AAQgIAPgMAQQgPASgMAJQgTAQgYAIQgXAHgWACIgMAAQgRAAgRgEgAIbB9IBEjkQACgJAHgHQAHgIAHgDQAOgIARAAIBSAAQASAAAOAEQAOAEAHAKQAKAPgEAeQgCAKgDAOQgFAOgGAKQgHANgKAIQgJAHgLAFQgMAGgOACQgQADgMAAIhEAAIgfBsgAKYhlQgCACgBADIgYBRIA3AAIANgCQAGAAAFgEQANgGAEgNIAHgSIAEgSQACgMgEgIQgCgDgFgDQgFgCgFAAIg2AAQgCAAgFADgA1eBSIAbgKIAjh2IgXAAIAJgdIAXAAIARg7IAuAAIgSA7IATAAIgIAdIgTAAIgeBjIAagJIgJAeIg0AVIg0ASgACjBjQgNAAgFgIQgEgIADgLIARg9QAEgKAJgGQAJgHAKAAIBFAAQAPAAAEAJQAFAHgDAMIgRA4QgDAMgIAHQgIAIgRAAgADMATIgCADIgNArIABADIADACIAaAAIADgCIACgDIANgrIgBgDQAAgBAAAAQgBAAAAgBQAAAAgBAAQAAAAgBAAIgZAAIgEACgADvgWIAAgdIAVAAQABAAAAAAQABAAAAAAQABgBAAAAQABAAABgBQACgBAAgDIAMgnIgBgEQAAgBAAAAQgBAAAAgBQgBAAAAAAQgBAAgBAAIgUAAQgGASgJAUIgNAVQgHALgKAKIgwAAQAJgJAJgLQAJgNAFgIQAJgSAHgVIgZAAIAJgeIBwAAQAGAAAGADQAEADACADQAFAIgDAMIgQA2QgEANgLAHQgIAHgPAAgARSghIAIgbIArAAIAHgYIg0AAIAIgbIA0AAIAGgXIAtAAIgGAXIAvAAIgIAbIgvAAIgHAYIAmAAIgIAbgAqtgkQgMAAgGgIIgCgIIABgJIAOgtQACgKAKgIQAJgIAKAAIC+AAQANAAAFAIQAGAHgEAOIgMApQgDAMgJAGQgJAIgLAAgAqPhCQAAABAAAAQAAABAAAAQAAAAAAABQAAAAABABQAAAAAAAAQAAABABAAQAAAAAAAAQABAAAAAAICMAAQAAAAABAAQAAAAABAAQAAAAABgBQAAAAABAAIACgDIACgIIiVAAgAqEhmIgCAHICUAAIADgHIgBgDQAAAAAAgBQgBAAAAAAQgBgBAAAAQgBAAAAAAIiLAAQgFAAgBAFgAjKguIgCgZIgRAXIhPAAQgKAAgDgHQgDgEABgGQACgGAFgFIA0g7IA1AAIg2A7IA0AAIAAgjIAtAAQgBAQACARQACASADAOg");

	this.instance = new lib.t1_s();
	this.instance.parent = this;
	this.instance.setTransform(-145,-20.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.C1_txt2, new cjs.Rectangle(-145,-20.5,290,41), null);


(lib.C1_txt1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 圖層_1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#D7D7D7","#FFFFFF"],[0,0.549],0,9.9,0,-9.8).s().p("AgyBiIAtiaIgiASIgKADIAIgbIAOgGIAOgJIAZgUIAmAAIg4DDg");
	this.shape.setTransform(-20.4,0);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#D7D7D7","#FFFFFF"],[0,0.549],0,10.1,0,-10.1).s().p("AghBkIgVgCQgKgCgJgHQgKgIgEgIIgDgIIgCgJIAAgKIACgKIAuAAIgCAOQAAAFADAGQADAIAHAEQAGADAJABQAKABAIgCQAIgDAGgEQAHgGAEgIQAEgIgBgHQgBgHgGgFQgGgGgLgCIgVgFQgLgDgKgEQgJgEgFgGQgGgGgCgKQgDgLACgHQABgKAFgJQAHgMAIgIQAIgJAMgGQALgFALgDQAOgCAKAAIAVABQANACAHADQAQAGAGAOIADAPIABATIgvAAIACgLQAAgFgCgGQgDgGgHgFQgHgDgIABQgGAAgHACQgGACgEAEQgGAEgEAGQgDAFgBAJQABAHAEAEQAFAEAGACIANAEIAOAEIAXAIQAKAEAIAHQAFAGABAIQACAJgCALQgCAMgIANQgIAMgLAJQgFAFgIAEIgOAFIgPAEIgNACIgKAAIgNgBg");
	this.shape_1.setTransform(-38.1,0.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#D7D7D7","#FFFFFF"],[0,0.549],0,9.9,0,-9.8).s().p("AhfBiQgFAAgCgCQgCgDAAgDQgBgEACgFQABgDAGgHICQiQIhkAAIAHgYICIAAQAFAAAEACQADACABADQACADgBAFQgCAFgEAEIiSCUIBtAAIgHAXg");
	this.shape_2.setTransform(-55.5,0);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["#D7D7D7","#FFFFFF"],[0,0.549],0,10.1,0,-10.1).s().p("AgsBkQgOgCgJgEQgJgEgIgIQgIgIgEgLQgFgPACgRQAAgRAHgSQAGgSAKgQQAKgRANgNQAJgIAMgIQAMgGAMgEQAIgDAMgCIAUgBQAOAAAJACQAMADAIAGQAJAFAFAIQAGAHADALQADAOAAAPQgBAPgFARQgFATgLARQgKATgQANQgPAOgUAIQgQAHgTABIgHAAIgUgBgAAAhGQgLAEgKALQgLALgHAQQgGAQgEANIgEAOIgCAQIAAAPIADAMQABAFAEAEQAEAEAFADQAGACAGABIAMgBIANgDIANgGQAFgDAHgHQAEgEAFgJIALgYIAJgYIAEgaQABgPgCgJQAAgFgEgFQgDgEgFgDQgDgCgHgCIgMgBQgNABgJAFg");
	this.shape_3.setTransform(-74.1,0.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.lf(["#D7D7D7","#FFFFFF"],[0,0.549],0,10.2,0,-10.1).s().p("AAoBmIgIgQIgPAQIgiAAQANgNAHgKIATgXIgHgrIgPAtQgGAUgOAYIgeAAQAIgPAKgXQAHgSAGgWIAaheQADgJAHgFQAGgEADAAIAJgCIAwgFIAwgGIgGAVIgTADIg/AHIgDABIgCADIgIAdIA7AAQAGAAADABQADACACADQACAFgBAEQAAAFgDAFIgVAiQgNAUgKANIAUAvgAAUgEIAYAAIAEAZIAUghIAAgCQAAgBAAAAQAAAAAAAAQgBgBAAAAQgBAAAAAAIgrAAgAhSBmIAWhJIgBgEIgDgBIgFAAIgNAnQgJAWgJARIgeAAIARgmQAIgUAFgTIAkh7IAfAAIgQA3IAJAAIARg5IAbAAIgPA5IAIAAIgHAVIguAAIgHAZIAWAAQAEAAADABIADAFQADAFgCAGIgYBSg");
	this.shape_4.setTransform(71.1,0);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.lf(["#D7D7D7","#FFFFFF"],[0,0.549],0,10.1,0,-10).s().p("AgKBlIAThGIgwAAIAFgSIAwAAIAEgMIgVAAQgEAAgDgBIgFgEQgDgFACgKIAMgoIgHAAIAGgUIAGAAIAFgSIAdAAIgFASIAKAAIAGgVIAaAAIgGAVIAMAAIAGgVIAaAAIgGAVIAQAAIgFAUIgRAAIgFARQgCAHgFAEQgFAFgHgBIgkAAQgGAAgCgEQgCgFABgGIAGgRIgLAAIgLAlIABADIACABIBQAAIgFATIgrAAIgDAMIAwAAIgFASIgxAAIgTBGgAA5gxIAAACIACACIAHAAQAAAAABAAQAAAAAAAAQABgBAAAAQAAAAAAgBIACgCIADgKIgNAAgAAqBeQgBgNAAgNIACgcIAeAAIgBAcQAAAOABAMgAg8BeIAfg2IAeAAIgcA2gAhsBYQgDAAgDgBIgEgEQgCgGACgGIAQg5IgKAAQAdgtAQgqIgPAAIAGgUIBGAAIgGAUIgXAAIgXAwIAMAAQAKAAADAEQADAFgDALIgWBMQgCAHgGAGIgGADQgEABgEAAgAhEgEIgBACIgUBDIAAACIACABIADAAQABAAAAAAQAAAAAAAAQABAAAAAAQAAgBAAAAIACgCIAThDIAAgCIgBgBIgDAAg");
	this.shape_5.setTransform(49.8,0);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.lf(["#D7D7D7","#FFFFFF"],[0,0.549],0,10.1,0,-10.1).s().p("AANBlIgfgPIgqAOIhBAAIBSgdIgigaIAxAAIARAMIAogSIh7AAIAGgSICiAAQAEABABACQACABABADIgBAHQgBADgEACIg/AfIAhAPIAgAPgAARAMQgDAAgCgBQgDgCgCgCQgBgFABgGIAOgxIgIAAIAQgXQAIgMAGgMIAcAAIgFAJIgGAIIAQAAIgBgRIAcAAIACARIAVAAIgFASIgYAAIgDAKIATAAIgEAPIgUAAIgCALIATAAIgEAPIgTAAIgEALIAaAAIgEAPgAAlgIIAAADIADACIALAAIAEgLIgQAAgAArgdIAPAAIADgLIgPAAgAAyg3IAQAAIADgKIgQAAgAhKAMQgJABgDgHQgDgGADgGIANgvIgKAAIAfgvIAcAAIgGAJIgGAIIAOAAIABgRIAbAAIAAARIARAAIgFASIgSAAIgDAKIAPAAIgFAPIgOAAIgEAKIAQAAIgEAQIgQAAIgDALIAUAAIgFAPgAg6gIIABADIACACIAJAAIAEgLIgOAAgAgzgeIANAAIACgKIgMAAgAgrg3IAMAAIADgKIgMAAg");
	this.shape_6.setTransform(27,0.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.lf(["#D7D7D7","#FFFFFF"],[0,0.549],0,10.1,0,-10).s().p("Ag2BiQgLgDgHgGQgHgHgDgKQgCgGAAgLQAAgIACgLIAsAAIgEAPQgCAGADAIQACAGAEADQAFACAFAAQAHgBAIgGQAHgFAFgLQAEgHAEgLQAEgKABgNQACgHgBgHQgCgGgFgDQgEgDgFAAQgFAAgGADQgHADgEAGIgGAHIgpAAIAlhXQADgIAHgFQAGgEAHAAIBeAAIgHAYIhEAAIgDABIgDADIgQApQAHgEAFgCQAHgDAGAAQAJgBAJADQAIACAGAFQAIAHADAJQAEAKgBAKQgCANgDALIgLAYQgHANgLAKQgKALgPAFQgLAFgQACIgIAAQgJAAgKgCg");
	this.shape_7.setTransform(-5.9,0.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.lf(["#D7D7D7","#FFFFFF"],[0,0.549],0,10.2,0,-10.1).s().p("Ag6BeQgLgJgEgRQgCgLABgMIADgYIAKgjQAGgSAKgRQAGgMAHgIQAFgIANgJQAIgGALgFQALgDALAAQANgBALAFQAKAFAGAJQAFAHACALQABAGAAANQgBARgEAOIgJAgQgFAOgHAPQgHAOgLAMQgNAPgOAGQgOAIgRAAIgCAAQgRAAgMgIgAAIhFQgIAHgHAPIgVBBIgEARIgDAMQgCAOAEAIQAFAIAHAAQAGAAAJgGQAHgGAGgNIAGgNIAVhHIACgNQABgPgDgHQgEgHgHgBQgHAAgIAGg");
	this.shape_8.setTransform(9.1,0);

	this.instance = new lib.t0_s();
	this.instance.parent = this;
	this.instance.setTransform(-91,-17.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.C1_txt1, new cjs.Rectangle(-91,-17.5,182,35), null);


(lib.C1_MOTOR_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 圖層_1
	this.instance = new lib.C1_MOTOR();
	this.instance.parent = this;
	this.instance.setTransform(-31,-45);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.C1_MOTOR_1, new cjs.Rectangle(-31,-45,62,90), null);


// stage content:
(lib._728x90 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// MASK (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_227 = new cjs.Graphics().p("AnuCWIBGkrIOXAAIhGErg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(227).to({graphics:mask_graphics_227,x:658.4,y:47}).wait(63));

	// LLLL
	this.instance = new lib.Shine();
	this.instance.parent = this;
	this.instance.setTransform(596.4,48.2,1,1.023,0,12.2,0,11.1,35.2);
	this.instance.alpha = 0.559;
	this.instance._off = true;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(227).to({_off:false},0).to({x:716.4,alpha:0.469},4).wait(59));

	// C3_BTN
	this.instance_1 = new lib.C3_btn();
	this.instance_1.parent = this;
	this.instance_1.setTransform(618.4,47);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(220).to({_off:false},0).to({x:658.4,alpha:1},4).wait(66));

	// C3_txt2
	this.instance_2 = new lib.C3_txt2();
	this.instance_2.parent = this;
	this.instance_2.setTransform(435.5,61.5);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(208).to({_off:false},0).to({x:475.5,alpha:1},6).wait(76));

	// C3_txt1
	this.instance_3 = new lib.C3_txt1();
	this.instance_3.parent = this;
	this.instance_3.setTransform(458.5,31.5);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(202).to({_off:false},0).to({x:488.5,alpha:1},6).wait(82));

	// C3_MOTOR
	this.instance_4 = new lib.C3_MOTOR_1();
	this.instance_4.parent = this;
	this.instance_4.setTransform(380.4,45);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(193).to({_off:false},0).to({x:290.4,alpha:0.5},2).to({x:320.4,alpha:1},2).wait(93));

	// C3_MOTOR_0
	this.instance_5 = new lib.C2_MOTOR_1();
	this.instance_5.parent = this;
	this.instance_5.setTransform(306.1,45);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(191).to({_off:false},0).to({x:216.1,alpha:0.5},2).to({x:246.1,alpha:1},2).wait(95));

	// CAR_LOGO 
	this.instance_6 = new lib.OSZ_LOGO_1();
	this.instance_6.parent = this;
	this.instance_6.setTransform(172,24.5);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(186).to({_off:false},0).to({alpha:1},5).wait(99));

	// C2_4v
	this.instance_7 = new lib.C2_4v();
	this.instance_7.parent = this;
	this.instance_7.setTransform(385,65.5,0.436,0.436,0,0,0,-92,-3);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(106).to({_off:false},0).to({scaleX:1,scaleY:1,alpha:1},6).wait(69).to({alpha:0},4).to({_off:true},1).wait(104));

	// C2_allview
	this.instance_8 = new lib.C2_allview();
	this.instance_8.parent = this;
	this.instance_8.setTransform(393,39.6,0.425,0.425,0,0,0,-85,7);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(94).to({_off:false},0).to({scaleX:1,scaleY:1,y:39.5,alpha:1},6).wait(81).to({alpha:0},4).to({_off:true},1).wait(104));

	// C2_usb
	this.instance_9 = new lib.C2_usb();
	this.instance_9.parent = this;
	this.instance_9.setTransform(315.3,36.9,0.256,0.256,0,0,0,73.9,-12.1);
	this.instance_9.alpha = 0;
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(82).to({_off:false},0).to({regX:74,regY:-12,scaleX:1,scaleY:1,x:307.5,y:42.5,alpha:1},6).wait(93).to({alpha:0},4).to({_off:true},1).wait(104));

	// C2_MOTOR
	this.instance_10 = new lib.C2_MOTOR_1();
	this.instance_10.parent = this;
	this.instance_10.setTransform(405,44.5,0.371,0.371);
	this.instance_10.alpha = 0;
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(77).to({_off:false},0).to({scaleX:1,scaleY:1,x:345,alpha:1},5).wait(99).to({alpha:0},4).to({_off:true},1).wait(104));

	// C1_txt2
	this.instance_11 = new lib.C1_txt2();
	this.instance_11.parent = this;
	this.instance_11.setTransform(421,30.9,0.289,0.289);
	this.instance_11.alpha = 0;
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(27).to({_off:false},0).to({regX:0.2,regY:0.1,scaleX:1.11,scaleY:1.11,x:539.4,y:47.7,alpha:0.5},2).to({regX:0,regY:0,scaleX:1,scaleY:1,x:524.1,y:45.5,alpha:1},2).wait(42).to({alpha:0},4).to({_off:true},1).wait(212));

	// C1_txt0
	this.instance_12 = new lib.C1_txt1();
	this.instance_12.parent = this;
	this.instance_12.setTransform(325.6,43,0.114,0.114);
	this.instance_12.alpha = 0;
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(25).to({_off:false},0).to({regX:0.3,regY:0.3,scaleX:1.36,scaleY:1.36,x:212.8,y:65.1,alpha:0.328},2).to({regX:0,regY:0,scaleX:1,scaleY:1,x:245,y:58.5,alpha:1},2).wait(44).to({alpha:0},4).to({_off:true},1).wait(212));

	// CAR_LOGO
	this.instance_13 = new lib.OSZ_LOGO_1();
	this.instance_13.parent = this;
	this.instance_13.setTransform(303.5,30.5,0.478,0.478);
	this.instance_13.alpha = 0.41;
	this.instance_13._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(23).to({_off:false},0).to({regX:0.1,regY:0.2,scaleX:1.42,scaleY:1.42,x:274.4,y:38.6,alpha:0.711},2).to({regX:0,regY:0,scaleX:1,scaleY:1,x:293.5,y:30.5,alpha:1},2).wait(46).to({alpha:0},4).to({_off:true},1).wait(212));

	// C1_MOTOR
	this.instance_14 = new lib.C1_MOTOR_1();
	this.instance_14.parent = this;
	this.instance_14.setTransform(349.6,26.7,0.589,0.589,0,0,0,0.1,0.3);
	this.instance_14.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).to({regY:0.2,scaleX:0.68,scaleY:0.68,x:353.9,y:30.7,alpha:1},2,cjs.Ease.get(1)).to({regX:0,regY:0.1,scaleX:0.82,scaleY:0.82,x:358.3,y:37.2},3,cjs.Ease.get(1)).to({x:363.3,y:42.2},2,cjs.Ease.get(1)).to({regY:0,scaleX:1,scaleY:1,y:45},3,cjs.Ease.get(1)).to({y:47.5},2).to({y:45},3).wait(5).to({y:43},3).to({y:45},3).wait(47).to({scaleX:1.29,scaleY:1.29,y:63,alpha:0},4).to({_off:true},1).wait(212));

	// LOGO
	this.instance_15 = new lib.LOGO();
	this.instance_15.parent = this;
	this.instance_15.setTransform(13,13);

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(290));

	// 20
	this.instance_16 = new lib._20();
	this.instance_16.parent = this;
	this.instance_16.setTransform(76,13);

	this.timeline.addTween(cjs.Tween.get(this.instance_16).wait(290));

	// S5 
	this.instance_17 = new lib.speed();
	this.instance_17.parent = this;
	this.instance_17.setTransform(564.7,57.5,0.57,1.105,0,-5.2,-164.7,0.4,1.1);
	this.instance_17.alpha = 0.629;

	this.timeline.addTween(cjs.Tween.get(this.instance_17).to({regX:0.5,x:444.6,y:45.4,alpha:0},3).wait(3).to({regX:0.4,x:564.7,y:57.5,alpha:0.629},0).to({regX:0.5,x:444.6,y:45.4,alpha:0},3).wait(3).to({regX:0.4,x:564.7,y:57.5,alpha:0.629},0).to({regX:0.5,x:444.6,y:45.4,alpha:0},3).wait(275));

	// S4 
	this.instance_18 = new lib.speed();
	this.instance_18.parent = this;
	this.instance_18.setTransform(521.3,45.7,1.358,0.537,0,3.5,-176.5,0.1,0.4);
	this.instance_18.alpha = 0.871;
	this.instance_18._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_18).wait(3).to({_off:false},0).to({regY:0.5,skewX:0.5,skewY:-179.5,x:361.3,y:30.8,alpha:0},3).wait(3).to({regY:0.4,skewX:3.5,skewY:-176.5,x:521.3,y:45.7,alpha:0.871},0).to({regY:0.5,skewX:0.5,skewY:-179.5,x:361.3,y:30.8,alpha:0},3).wait(3).to({regY:0.4,skewX:3.5,skewY:-176.5,x:521.3,y:45.7,alpha:0.871},0).to({regY:0.5,skewX:0.5,skewY:-179.5,x:361.3,y:30.8,alpha:0},3).wait(272));

	// S3 
	this.instance_19 = new lib.speed();
	this.instance_19.parent = this;
	this.instance_19.setTransform(666.1,32.7,0.537,0.537,0,-0.3,179.7,0.1,0.3);
	this.instance_19.alpha = 0.91;

	this.timeline.addTween(cjs.Tween.get(this.instance_19).to({x:363.6,alpha:0.051},3).wait(3).to({x:666.1,alpha:0.91},0).to({x:363.6,alpha:0.051},3).wait(3).to({x:666.1,alpha:0.91},0).to({x:363.6,alpha:0.051},3).wait(275));

	// S2 
	this.instance_20 = new lib.speed();
	this.instance_20.parent = this;
	this.instance_20.setTransform(532.8,25,0.75,0.75,0,-0.3,179.7,0.1,0.2);
	this.instance_20.alpha = 0.488;
	this.instance_20._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_20).wait(3).to({_off:false},0).to({x:453.5,y:29.8,alpha:0},3).wait(3).to({x:532.8,y:25,alpha:0.488},0).to({x:453.5,y:29.8,alpha:0},3).wait(3).to({x:532.8,y:25,alpha:0.488},0).to({x:453.5,y:29.8,alpha:0},3).wait(272));

	// S1 
	this.instance_21 = new lib.speed();
	this.instance_21.parent = this;
	this.instance_21.setTransform(679.1,37,1,1,0,2.2,-177.8);
	this.instance_21.alpha = 0.828;

	this.timeline.addTween(cjs.Tween.get(this.instance_21).to({x:476,y:31.5,alpha:0},3).wait(3).to({x:679.1,y:37,alpha:0.828},0).to({x:476,y:31.5,alpha:0},3).wait(3).to({x:679.1,y:37,alpha:0.828},0).to({x:476,y:31.5,alpha:0},3).to({_off:true},257).wait(18));

	// S5
	this.instance_22 = new lib.speed();
	this.instance_22.parent = this;
	this.instance_22.setTransform(100.6,68,0.57,1.105,0,5.2,-15.3,0.4,1.1);
	this.instance_22.alpha = 0.629;

	this.timeline.addTween(cjs.Tween.get(this.instance_22).to({regX:0.5,x:220.8,y:55.9,alpha:0},3).wait(3).to({regX:0.4,x:100.6,y:68,alpha:0.629},0).to({regX:0.5,x:220.8,y:55.9,alpha:0},3).wait(3).to({regX:0.4,x:100.6,y:68,alpha:0.629},0).to({regX:0.5,x:220.8,y:55.9,alpha:0},3).wait(275));

	// S4
	this.instance_23 = new lib.speed();
	this.instance_23.parent = this;
	this.instance_23.setTransform(144,56.2,1.358,0.537,-3.5,0,0,0.1,0.4);
	this.instance_23.alpha = 0.871;
	this.instance_23._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_23).wait(3).to({_off:false},0).to({regY:0.5,rotation:-0.5,x:304,y:41.3,alpha:0},3).wait(3).to({regY:0.4,rotation:-3.5,x:144,y:56.2,alpha:0.871},0).to({regY:0.5,rotation:-0.5,x:304,y:41.3,alpha:0},3).wait(3).to({regY:0.4,rotation:-3.5,x:144,y:56.2,alpha:0.871},0).to({regY:0.5,rotation:-0.5,x:304,y:41.3,alpha:0},3).wait(272));

	// S3
	this.instance_24 = new lib.speed();
	this.instance_24.parent = this;
	this.instance_24.setTransform(-0.7,43.2,0.537,0.537,0.3,0,0,0.1,0.3);
	this.instance_24.alpha = 0.91;

	this.timeline.addTween(cjs.Tween.get(this.instance_24).to({x:301.8,alpha:0.051},3).wait(3).to({x:-0.7,alpha:0.91},0).to({x:301.8,alpha:0.051},3).wait(3).to({x:-0.7,alpha:0.91},0).to({x:301.8,alpha:0.051},3).wait(275));

	// S2
	this.instance_25 = new lib.speed();
	this.instance_25.parent = this;
	this.instance_25.setTransform(132.6,35.5,0.75,0.75,0.3,0,0,0.1,0.2);
	this.instance_25.alpha = 0.488;
	this.instance_25._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_25).wait(3).to({_off:false},0).to({x:211.9,y:40.3,alpha:0},3).wait(3).to({x:132.6,y:35.5,alpha:0.488},0).to({x:211.9,y:40.3,alpha:0},3).wait(3).to({x:132.6,y:35.5,alpha:0.488},0).to({x:211.9,y:40.3,alpha:0},3).wait(272));

	// S1
	this.instance_26 = new lib.speed();
	this.instance_26.parent = this;
	this.instance_26.setTransform(-13.7,47.5,1,1,-2.2);
	this.instance_26.alpha = 0.828;

	this.timeline.addTween(cjs.Tween.get(this.instance_26).to({x:189.3,y:42,alpha:0},3).wait(3).to({x:-13.7,y:47.5,alpha:0.828},0).to({x:189.3,y:42,alpha:0},3).wait(3).to({x:-13.7,y:47.5,alpha:0.828},0).to({x:189.3,y:42,alpha:0},3).to({_off:true},257).wait(18));

	// BG
	this.instance_27 = new lib.BG();
	this.instance_27.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_27).wait(290));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(338.2,45,753.9,90.1);
// library properties:
lib.properties = {
	id: '90D9EA7C91367D4B8002D20983FE3591',
	width: 728,
	height: 90,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/_20.png?1520926525649", id:"_20"},
		{src:"images/_4v_s.png?1520926525649", id:"_4v_s"},
		{src:"images/allview_s.png?1520926525649", id:"allview_s"},
		{src:"images/BG.png?1520926525649", id:"BG"},
		{src:"images/C1_MOTOR.png?1520926525649", id:"C1_MOTOR"},
		{src:"images/C2_MOTOR.png?1520926525649", id:"C2_MOTOR"},
		{src:"images/C3_MOTOR.png?1520926525649", id:"C3_MOTOR"},
		{src:"images/C3_txt1_s.png?1520926525649", id:"C3_txt1_s"},
		{src:"images/C3_txt2_s.png?1520926525649", id:"C3_txt2_s"},
		{src:"images/LOGO.png?1520926525650", id:"LOGO"},
		{src:"images/OSZ_LOGO.png?1520926525650", id:"OSZ_LOGO"},
		{src:"images/t0_s.png?1520926525650", id:"t0_s"},
		{src:"images/t1_s.png?1520926525650", id:"t1_s"},
		{src:"images/usb_s.png?1520926525650", id:"usb_s"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['90D9EA7C91367D4B8002D20983FE3591'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;